<?php

/**
 * @file
 */

/**
 * Implements hook_FORM_ID_alter().
 *
 * Add fields to a form, letting the administrator choose the various theme
 * settings.
 */
function loop_configure_theme_form_system_theme_settings_alter(&$form, $form_state) {
  $form['header'] = array(
    '#type' => 'fieldset',
    '#title' => t('Header'),
    '#collapsible' => FALSE,
    '#description' => t("Settings for the page header"),
  );

  $form['header']['header_color'] = array(
    '#type'          => 'style_settings_colorpicker',
    '#title'         => t('Header background color'),
    '#default_value' => theme_get_setting('header_color', 'loop'),
    '#description'   => t("Choose a color for the header background"),
  );

  $form['header']['header_logo_height'] = array(
    '#type'          => 'textfield',
    '#title'         => t('Header logo height'),
    '#default_value' => theme_get_setting('header_logo_height', 'loop'),
    '#description'   => t("Choose a height for the header logo"),
  );

  $form['terms_keywords'] = array(
    '#type' => 'fieldset',
    '#title' => t('Term/keyword buttons'),
    '#collapsible' => FALSE,
    '#description' => t("Settings for the term/keyword buttons"),
  );

  $form['terms_keywords']['term_background_color'] = array(
    '#type'          => 'style_settings_colorpicker',
    '#title'         => t('Term background color'),
    '#default_value' => theme_get_setting('term_background_color', 'loop'),
    '#description'   => t("Choose a color for the term background"),
  );

  $form['terms_keywords']['term_hover_background_color'] = array(
    '#type'          => 'style_settings_colorpicker',
    '#title'         => t('Term hover background color'),
    '#default_value' => theme_get_setting('term_hover_background_color', 'loop'),
    '#description'   => t("Choose a color for the term background on hover"),
  );

  $form['terms_keywords']['keyword_background_color'] = array(
    '#type'          => 'style_settings_colorpicker',
    '#title'         => t('Keyword background color'),
    '#default_value' => theme_get_setting('keyword_background_color', 'loop'),
    '#description'   => t("Choose a color for the keyword background"),
  );

  $form['terms_keywords']['keyword_hover_background_color'] = array(
    '#type'          => 'style_settings_colorpicker',
    '#title'         => t('Keyword hover background color'),
    '#default_value' => theme_get_setting('keyword_hover_background_color', 'loop'),
    '#description'   => t("Choose a color for the keyword background on hover"),
  );

  $form['terms_keywords']['content_type_label_color_default'] = array(
    '#type'          => 'style_settings_colorpicker',
    '#title'         => t('Content type default label color'),
    '#default_value' => theme_get_setting('content_type_label_color_default', 'loop'),
    '#description'   => t("Choose a default color for the content type color label"),
  );

  $form['terms_keywords']['content_type_label_color_post'] = array(
    '#type'          => 'style_settings_colorpicker',
    '#title'         => t('Content type post label color'),
    '#default_value' => theme_get_setting('content_type_label_color_post', 'loop'),
    '#description'   => t("Choose a color for the post color label"),
  );

  $form['terms_keywords']['content_type_label_text_color_default'] = array(
    '#type'          => 'style_settings_colorpicker',
    '#title'         => t('Content type default label text color'),
    '#default_value' => theme_get_setting('content_type_label_text_color_default', 'loop'),
    '#description'   => t("Choose a default color for the content type color label text"),
  );

  $form['terms_keywords']['content_type_label_text_color_post'] = array(
    '#type'          => 'style_settings_colorpicker',
    '#title'         => t('Content type post label text color'),
    '#default_value' => theme_get_setting('content_type_label_text_color_post', 'loop'),
    '#description'   => t("Choose a color for the post color label text"),
  );

  $form['#submit'][] = 'loop_configure_theme_flush';
}

/**
 *
 */
function loop_configure_theme_flush() {
  _drupal_flush_css_js();
  cache_clear_all('style_settings_', 'cache', TRUE);
}
