<?php
/**
 * Implements hook_FORM_ID_alter().
 *
 * Add fields to a form, letting the administrator choose the header color and logo height.
 */
function loop_configure_theme_form_system_theme_settings_alter(&$form, $form_state) {
  $form['logout_settings'] = array(
    '#type' => 'fieldset',
    '#title' => t('Logout button settings'),
    '#collapsible' => FALSE,
    '#description' => t("Settings determining behaviour of the logout button"),
  );

  $form['logout_settings']['show_logout_for_regular_users'] = array(
    '#type' => 'checkbox',
    '#title' => t('Show logout button for regular users'),
    '#default_value' => theme_get_setting('show_logout_for_regular_users', 'loop'),
    '#description' => t("Show logout button when logged in as a regular user"),
  );

  $form['logout_settings']['show_logout_for_saml_users'] = array(
    '#type' => 'checkbox',
    '#title' => t('Show logout button for SAML users'),
    '#default_value' => theme_get_setting('show_logout_for_saml_users', 'loop'),
    '#description' => t("Show logout button when logged via SAML"),
  );

  $form['header'] = array(
    '#type' => 'fieldset',
    '#title' => t('Header'),
    '#collapsible' => FALSE,
    '#description' => t("Settings for the page header"),
  );

  $form['header']['header_color'] = array(
    '#type'          => 'style_settings_colorpicker',
    '#title'         => t('Header background color'),
    '#default_value' => theme_get_setting('header_color', 'loop'),
    '#description'   => t("Choose a color for the header background"),
  );

  $form['header']['header_logo_height'] = array(
    '#type'          => 'textfield',
    '#title'         => t('Header logo height'),
    '#default_value' => theme_get_setting('header_logo_height', 'loop'),
    '#description'   => t("Choose a height for the header logo"),
  );

  $form['#submit'][] = 'loop_configure_theme_flush';
}

function loop_configure_theme_flush() {
  _drupal_flush_css_js();
  cache_clear_all('style_settings_', 'cache', TRUE);
}
