<?php

/**
 * @file Secure Permissions Data
 * Module file for secure permissions in code.
 */

/**
 * Define site roles in code.
 *
 * Create a secure_permissions_data module directory and place this function
 * in secure_permissions_data.module.
 *
 * @return
 *   An array defining all the roles for the site.
 */
function secure_permissions_data_secure_permissions_roles() {
  return array(
      'anonymous user',
      'authenticated user',
      'administrator',
      'documentation coordinator',
      'manager',
  );
}

/**
 * Define site permissions in code.
 *
 * Create a secure_permissions_data module directory and place this function
 * in secure_permissions_data.module.
 *
 * @param $role
 *   The role for which the permissions are being requested.
 *
 * @return
 *   An array defining all the permissions for the site.
 */
function secure_permissions_data_secure_permissions($role) {
  $permissions = array(
      'anonymous user' => array(
      ),
      'authenticated user' => array(
          'access comments',
          'access content',
          'access search_api_page',
          'access statistics',
          'access user profiles',
          'create post content',
          'edit own comments',
          'edit own post content',
          'flag ranking',
          'flag subscribe_node',
          'post comments',
          'skip comment approval',
          'unflag ranking',
          'unflag subscribe_node',
          'view own unpublished content',
          'view post access counter',
      ),
      'administrator' => array(
          'access administration pages',
          'access all views',
          'access content overview',
          'access contextual links',
          'access own authorizations',
          'access own consumers',
          'access rules debug',
          'access site in maintenance mode',
          'access site reports',
          'access statistics',
          'access toolbar',
          'access user profiles',
          'administer actions',
          'administer advanced pane settings',
          'administer blocks',
          'administer comments',
          'administer consumers',
          'administer content types',
          'administer facets',
          'administer features',
          'administer fieldgroups',
          'administer filters',
          'administer flags',
          'administer google analytics',
          'administer google analytics counter',
          'administer group',
          'administer image styles',
          'administer languages',
          'administer menu',
          'administer message subscribe',
          'administer message types',
          'administer meta tags',
          'administer module filter',
          'administer modules',
          'administer nodes',
          'administer oauth',
          'administer page manager',
          'administer page titles',
          'administer pane access',
          'administer panels layouts',
          'administer panels styles',
          'administer pathauto',
          'administer pcp',
          'administer permissions',
          'administer redirects',
          'administer rules',
          'administer search_api',
          'administer site configuration',
          'administer software updates',
          'administer statistics',
          'administer taxonomy',
          'administer themes',
          'administer url aliases',
          'administer users',
          'administer uuid',
          'administer views',
          'block IP addresses',
          'bypass node access',
          'bypass rules access',
          'cancel account',
          'change layouts in place editing',
          'change own username',
          'create messages',
          'create page content',
          'create url aliases',
          'delete any page content',
          'delete any post content',
          'delete own page content',
          'delete own post content',
          'delete revisions',
          'delete terms in 1',
          'delete terms in 2',
          'delete terms in 3',
          'edit any page content',
          'edit any post content',
          'edit meta tags',
          'edit own page content',
          'edit terms in 1',
          'edit terms in 2',
          'edit terms in 3',
          'export nodes',
          'export own nodes',
          'export secure permissions',
          'generate features',
          'manage features',
          'notify of path changes',
          'oauth authorize any consumers',
          'oauth register any consumers',
          'opt-in or out of tracking',
          'revert revisions',
          'select account cancellation method',
          'set page title',
          'translate interface',
          'use flag import',
          'use page manager',
          'use panels caching features',
          'use panels dashboard',
          'use panels in place editing',
          'use panels locks',
          'use PHP for label patterns',
          'use PHP for tracking visibility',
          'use PHP to import nodes',
          'use text format editor',
          'view pane admin links',
          'view revisions',
          'view the administration theme',
      ),
      'documentation coordinator' => array(
          'access content overview',
          'access user profiles',
          'administer nodes',
          'create page content',
          'delete any page content',
          'delete any post content',
          'delete own page content',
          'delete own post content',
          'delete revisions',
          'edit any page content',
          'edit any post content',
          'edit own page content',
          'revert revisions',
          'use text format editor',
          'view revisions',
      ),
      'manager' => array(
          'access content overview',
          'access contextual links',
          'access user profiles',
          'administer nodes',
          'create page content',
          'delete any page content',
          'delete any post content',
          'delete own page content',
          'delete own post content',
          'delete revisions',
          'edit any page content',
          'edit any post content',
          'edit own page content',
          'revert revisions',
          'use text format editor',
          'view revisions',
      ),
  );
  if (isset($permissions[$role])) {
    return $permissions[$role];
  }
}