<?php
/**
 * @file
 * Code for the Loop Notificaiton feature.
 */

include_once 'loop_notification.features.inc';

/**
 * Implements hook_form_ID_alter().
 */
function loop_notification_form_notifications_account_subscription_list_form_alter(&$form, $form_state) {
  // Add comments column.
  $form['subscriptions']['#header']['comments'] = array(
    'data' => t('Comments'),
  );

  foreach ($form['subscriptions']['#options'] as $sid => $value) {
    // Load every subscription the user got, and figure out if any new comments
    // happens to be there.
    $ns = new Notifications_Subscription();
    $nns = $ns->load($sid);

    $comments = comment_num_new($nns->fields[0]->value);

    $form['subscriptions']['#options'][$sid]['comments'] = $comments;
  }
}
