<?php
/**
 * @file
 * Code for the Loop External data feature.
 */

include_once 'loop_external_data.features.inc';
include 'parser.php';
include 'iParser.inc';
include 'Node.php';
include 'LoopIndex.php';
include 'Leaf.php';
include 'Tree.php';


/**
 * Implements hook_node_insert().
 */
function loop_external_data_node_insert($node) {
  if ($node->type == 'index') {
    _loop_external_data_file_load($node);
  }
}

/**
 * Implements hook_node_update().
 */
function loop_external_data_node_update($node) {
  if ($node->type == 'index') {
    _loop_external_data_file_load($node);
  }
}

function _loop_external_data_file_load($node) {
  $wrapper = entity_metadata_wrapper('node', $node);
  $file_fid = $wrapper->field_file->value();

  $file = file_load($file_fid['fid']);

  $parser = new Parser();
  $data = $parser->parse(drupal_realpath($file->uri), drupal_realpath('public://index_file/' . $file->fid));

  // Check if data is returned.
  if (!empty($data)) {
    // Send data and node id to parser.
    _loop_external_data_parser($data, $node->nid);
  }
}

function _loop_external_data_parser($data, $parent = NULL) {
  foreach ($data as $index) {
    switch ($index->type) {
      case 'tree':
        _loop_external_data_parser_tree($index, $parent);
        break;

      case 'leaf':
        _loop_external_data_parser_leaf($index, $parent);
        break;
    }
  }
}

function _loop_external_data_parser_tree($tree, $parent = NULL) {
  global $user;
  $node = new Stdclass();

  $node->type = 'tree';
  $node->status = 1;
  $node->uid = $user->uid;
  $node->title = $tree->title;

  node_save($node);

  foreach ($tree->childern as $child) {
    _loop_external_data_parser($child, $node->nid);
  }

  // Load parent node and add the leaf.
  $parentNode = node_load($parent);
  $wrapper = entity_metadata_wrapper('node', $parentNode);
  $wrapper->field_leaf->set($node->nid);
  node_save($parentNode);
}

function _loop_external_data_parser_leaf($leaf, $parent = NULL) {
  global $user;
  $node = new Stdclass();

  $node->type = 'leaf';
  $node->status = 1;
  $node->uid = $user->uid;
  $node->title = $leaf->title;

  $wrapper = entity_metadata_wrapper('node', $node);
  $wrapper->body->set($leaf->body);
  node_save($node);

  // Load parent node and add the leaf.
  $parentNode = node_load($parent);
  $wrapper = entity_metadata_wrapper('node', $parentNode);
  $wrapper->field_leaf->set($node->nid);
  node_save($parentNode);
}

