<?php
/**
 * @file
 * loop_example_content.features.node_export_features.inc
 */

/**
 * Implements hook_node_export_features_default().
 */
function loop_example_content_node_export_features_default() {
  $node_export = array(
  'code_string' => 'array(
  (object) array(
      \'vid\' => \'113\',
      \'uid\' => \'1\',
      \'title\' => \' Skal borgerkonsulenterne fortsat sende deres adviser til de forskellige lederpostkasser?\',
      \'log\' => \'\',
      \'status\' => \'1\',
      \'comment\' => \'2\',
      \'promote\' => \'0\',
      \'sticky\' => \'0\',
      \'vuuid\' => \'4426ec8b-a481-4b71-b715-6785c2634332\',
      \'nid\' => \'113\',
      \'type\' => \'post\',
      \'language\' => \'und\',
      \'created\' => \'1391089175\',
      \'changed\' => \'1391089175\',
      \'tnid\' => \'0\',
      \'translate\' => \'0\',
      \'uuid\' => \'97256af2-26c6-49bb-9c22-4453e3c25b05\',
      \'revision_timestamp\' => \'1391089175\',
      \'revision_uid\' => \'0\',
      \'field_description\' => array(
        \'und\' => array(
          array(
            \'value\' => \' Skal borgerkonsulenterne fortsat sende deres adviser til de forskellige lederpostkasser?\',
            \'format\' => NULL,
            \'safe_value\' => \' Skal borgerkonsulenterne fortsat sende deres adviser til de forskellige lederpostkasser?\',
          ),
        ),
      ),
      \'field_keyword\' => array(
        \'und\' => array(
          array(
            \'tid\' => \'23\',
          ),
        ),
      ),
      \'field_profession\' => array(
        \'und\' => array(
          array(
            \'tid\' => \'84\',
          ),
        ),
      ),
      \'field_subject\' => array(
        \'und\' => array(
          array(
            \'tid\' => \'52\',
          ),
        ),
      ),
      \'metatags\' => array(),
      \'cid\' => \'0\',
      \'last_comment_timestamp\' => \'1391089175\',
      \'last_comment_name\' => NULL,
      \'last_comment_uid\' => \'0\',
      \'comment_count\' => \'0\',
      \'notifications_status\' => \'1\',
      \'name\' => \'admin\',
      \'picture\' => \'0\',
      \'data\' => \'b:0;\',
      \'path\' => array(
        \'pid\' => \'251\',
        \'source\' => \'node/113\',
        \'alias\' => \'content/skal-borgerkonsulenterne-fortsat-sende-deres-adviser-til-de-forskellige-lederpostkasser\',
        \'language\' => \'und\',
      ),
      \'menu\' => NULL,
      \'node_export_drupal_version\' => \'7\',
    ),
  (object) array(
      \'vid\' => \'114\',
      \'uid\' => \'1\',
      \'title\' => \' Hvordan dokumenteres delvis aktindsigt? Og findes der en vejledning i dokumentation af aktindsigt?\',
      \'log\' => \'\',
      \'status\' => \'1\',
      \'comment\' => \'2\',
      \'promote\' => \'0\',
      \'sticky\' => \'0\',
      \'vuuid\' => \'8068912d-ae0d-4e09-9490-d499eabeb008\',
      \'nid\' => \'114\',
      \'type\' => \'post\',
      \'language\' => \'und\',
      \'created\' => \'1391089175\',
      \'changed\' => \'1391089175\',
      \'tnid\' => \'0\',
      \'translate\' => \'0\',
      \'uuid\' => \'aeadca1e-824e-4908-a066-692747c111b6\',
      \'revision_timestamp\' => \'1391089175\',
      \'revision_uid\' => \'0\',
      \'field_description\' => array(
        \'und\' => array(
          array(
            \'value\' => \' Hvordan dokumenteres delvis aktindsigt? Og findes der en vejledning i dokumentation af aktindsigt?\',
            \'format\' => NULL,
            \'safe_value\' => \' Hvordan dokumenteres delvis aktindsigt? Og findes der en vejledning i dokumentation af aktindsigt?\',
          ),
        ),
      ),
      \'field_keyword\' => array(),
      \'field_profession\' => array(),
      \'field_subject\' => array(
        \'und\' => array(
          array(
            \'tid\' => \'11\',
          ),
        ),
      ),
      \'metatags\' => array(),
      \'cid\' => \'0\',
      \'last_comment_timestamp\' => \'1391089175\',
      \'last_comment_name\' => NULL,
      \'last_comment_uid\' => \'0\',
      \'comment_count\' => \'0\',
      \'notifications_status\' => \'1\',
      \'name\' => \'admin\',
      \'picture\' => \'0\',
      \'data\' => \'b:0;\',
      \'path\' => array(
        \'pid\' => \'252\',
        \'source\' => \'node/114\',
        \'alias\' => \'content/hvordan-dokumenteres-delvis-aktindsigt-og-findes-der-en-vejledning-i-dokumentation-af\',
        \'language\' => \'und\',
      ),
      \'menu\' => NULL,
      \'node_export_drupal_version\' => \'7\',
    ),
  (object) array(
      \'vid\' => \'115\',
      \'uid\' => \'1\',
      \'title\' => \' Hvad gør vi når vi overtager en GOP som er startet på og adr. til Vikjærgården( som udfører) eller et andet lokalcenter?\',
      \'log\' => \'\',
      \'status\' => \'1\',
      \'comment\' => \'2\',
      \'promote\' => \'0\',
      \'sticky\' => \'0\',
      \'vuuid\' => \'e5fcac1c-d99f-4a10-9f97-2a68811c2bb6\',
      \'nid\' => \'115\',
      \'type\' => \'post\',
      \'language\' => \'und\',
      \'created\' => \'1391089175\',
      \'changed\' => \'1391089175\',
      \'tnid\' => \'0\',
      \'translate\' => \'0\',
      \'uuid\' => \'b24a4456-3e19-4320-99e4-4c97869d6c63\',
      \'revision_timestamp\' => \'1391089175\',
      \'revision_uid\' => \'0\',
      \'field_description\' => array(
        \'und\' => array(
          array(
            \'value\' => \' Hvad gør vi når vi overtager en GOP som er startet på og adr. til Vikjærgården( som udfører) eller et andet lokalcenter?\',
            \'format\' => NULL,
            \'safe_value\' => \' Hvad gør vi når vi overtager en GOP som er startet på og adr. til Vikjærgården( som udfører) eller et andet lokalcenter?\',
          ),
        ),
      ),
      \'field_keyword\' => array(),
      \'field_profession\' => array(
        \'und\' => array(
          array(
            \'tid\' => \'47\',
          ),
        ),
      ),
      \'field_subject\' => array(
        \'und\' => array(
          array(
            \'tid\' => \'53\',
          ),
        ),
      ),
      \'metatags\' => array(),
      \'cid\' => \'0\',
      \'last_comment_timestamp\' => \'1391089175\',
      \'last_comment_name\' => NULL,
      \'last_comment_uid\' => \'0\',
      \'comment_count\' => \'0\',
      \'notifications_status\' => \'1\',
      \'name\' => \'admin\',
      \'picture\' => \'0\',
      \'data\' => \'b:0;\',
      \'path\' => array(
        \'pid\' => \'253\',
        \'source\' => \'node/115\',
        \'alias\' => \'content/hvad-gør-vi-når-vi-overtager-en-gop-som-er-startet-på-og-adr-til-vikjærgården-som-udfører\',
        \'language\' => \'und\',
      ),
      \'menu\' => NULL,
      \'node_export_drupal_version\' => \'7\',
    ),
  (object) array(
      \'vid\' => \'116\',
      \'uid\' => \'1\',
      \'title\' => \' Skal terapeuter låse funktionsvurderingen, når de tildeler en ydelse?\',
      \'log\' => \'\',
      \'status\' => \'1\',
      \'comment\' => \'2\',
      \'promote\' => \'0\',
      \'sticky\' => \'0\',
      \'vuuid\' => \'8835cfd1-e38c-4c55-8e6c-98855353144f\',
      \'nid\' => \'116\',
      \'type\' => \'post\',
      \'language\' => \'und\',
      \'created\' => \'1391089175\',
      \'changed\' => \'1391089175\',
      \'tnid\' => \'0\',
      \'translate\' => \'0\',
      \'uuid\' => \'deee00a7-f716-4ecc-bbfa-76e541e7a6c5\',
      \'revision_timestamp\' => \'1391089175\',
      \'revision_uid\' => \'0\',
      \'field_description\' => array(
        \'und\' => array(
          array(
            \'value\' => \' Skal terapeuter låse funktionsvurderingen, når de tildeler en ydelse?\',
            \'format\' => NULL,
            \'safe_value\' => \' Skal terapeuter låse funktionsvurderingen, når de tildeler en ydelse?\',
          ),
        ),
      ),
      \'field_keyword\' => array(
        \'und\' => array(
          array(
            \'tid\' => \'28\',
          ),
        ),
      ),
      \'field_profession\' => array(
        \'und\' => array(
          array(
            \'tid\' => \'84\',
          ),
        ),
      ),
      \'field_subject\' => array(
        \'und\' => array(
          array(
            \'tid\' => \'53\',
          ),
        ),
      ),
      \'metatags\' => array(),
      \'cid\' => \'0\',
      \'last_comment_timestamp\' => \'1391089175\',
      \'last_comment_name\' => NULL,
      \'last_comment_uid\' => \'0\',
      \'comment_count\' => \'0\',
      \'notifications_status\' => \'1\',
      \'name\' => \'admin\',
      \'picture\' => \'0\',
      \'data\' => \'b:0;\',
      \'path\' => array(
        \'pid\' => \'254\',
        \'source\' => \'node/116\',
        \'alias\' => \'content/skal-terapeuter-låse-funktionsvurderingen-når-de-tildeler-en-ydelse\',
        \'language\' => \'und\',
      ),
      \'menu\' => NULL,
      \'node_export_drupal_version\' => \'7\',
    ),
  (object) array(
      \'vid\' => \'117\',
      \'uid\' => \'1\',
      \'title\' => \'Er det tilstrækkeligt i forhold til sygeplejefaglig udredning, at en ydelse er tildelt og at de 12 sygeplejefaglige målepunkter er udfyldt under Samlet faglig vurdering?\',
      \'log\' => \'\',
      \'status\' => \'1\',
      \'comment\' => \'2\',
      \'promote\' => \'0\',
      \'sticky\' => \'0\',
      \'vuuid\' => \'99d1cbdf-fdc4-4c4c-97a3-0f6e954d8b36\',
      \'nid\' => \'117\',
      \'type\' => \'post\',
      \'language\' => \'und\',
      \'created\' => \'1391089175\',
      \'changed\' => \'1391089175\',
      \'tnid\' => \'0\',
      \'translate\' => \'0\',
      \'uuid\' => \'f7fc65c1-a6cf-4cc5-854c-7c6dbd76f5d6\',
      \'revision_timestamp\' => \'1391089175\',
      \'revision_uid\' => \'0\',
      \'field_description\' => array(
        \'und\' => array(
          array(
            \'value\' => \'Er det tilstrækkeligt i forhold til sygeplejefaglig udredning, at en ydelse er tildelt og at de 12 sygeplejefaglige målepunkter er udfyldt under Samlet faglig vurdering?\',
            \'format\' => NULL,
            \'safe_value\' => \'Er det tilstrækkeligt i forhold til sygeplejefaglig udredning, at en ydelse er tildelt og at de 12 sygeplejefaglige målepunkter er udfyldt under Samlet faglig vurdering?\',
          ),
        ),
      ),
      \'field_keyword\' => array(),
      \'field_profession\' => array(
        \'und\' => array(
          array(
            \'tid\' => \'47\',
          ),
        ),
      ),
      \'field_subject\' => array(
        \'und\' => array(
          array(
            \'tid\' => \'11\',
          ),
        ),
      ),
      \'metatags\' => array(),
      \'cid\' => \'0\',
      \'last_comment_timestamp\' => \'1391089175\',
      \'last_comment_name\' => NULL,
      \'last_comment_uid\' => \'0\',
      \'comment_count\' => \'0\',
      \'notifications_status\' => \'1\',
      \'name\' => \'admin\',
      \'picture\' => \'0\',
      \'data\' => \'b:0;\',
      \'path\' => array(
        \'pid\' => \'255\',
        \'source\' => \'node/117\',
        \'alias\' => \'content/er-det-tilstrækkeligt-i-forhold-til-sygeplejefaglig-udredning-en-ydelse-er-tildelt-og-de-12\',
        \'language\' => \'und\',
      ),
      \'menu\' => NULL,
      \'node_export_drupal_version\' => \'7\',
    ),
)',
);
  return $node_export;
}
