<?php
/**
 * @file
 * Code for the Loop external sources content feature.
 */

include_once 'loop_external_sources_content.features.inc';


/**
 * Implements hook_menu().
 */
function loop_external_sources_content_menu() {
  $items['loop_search_nodes'] = array(
    'title' => 'List nodes in JSON format',
    'page callback' => 'loop_search_nodes',
    'type' => MENU_CALLBACK,
    'access arguments' => array('access content'),
  );

  $items['loop_external_soruces/%'] = array(
    'title' => 'List external sources in JSON format',
    'page callback' => 'loop_external_sources_content_documents',
    'page arguments' => array(1),
    'type' => MENU_CALLBACK,
    'access arguments' => array('access content'),
  );

  return $items;
}

/**
 * Find external sources and output as JSON.
 *
 * @param string $scope
 *   Comma separated list to search for.
 *
 * @return string
 *   JSON object.
 */
function loop_external_sources_content_documents($scope) {
  // Explode to array.
  $titles = explode(',', $scope);

  // Title filter.
  $or = db_or();
  foreach ($titles as $title) {
    $or->condition("title", $title . "%", 'LIKE');
  }

  // Fetch node ID and tiitle.
  $nodes = db_select('node', 'n')
    ->fields('n', array('nid', 'title'))
    ->condition('type', 'external_sources')
    ->condition('status', 1)
    ->condition($or)
    ->execute();

  $data = array();
  foreach ($nodes as $node) {
    $data[] = array(
      // For better search, use strtolower().
      'value' => strtolower(trim($node->title)),
      // Fine human output.
      'title' => trim($node->title),
      // Use internal path.
      'link' => '/' . drupal_get_path_alias('node/' . $node->nid),
    );
  }

  // Return as JSON.
  drupal_json_output($data);
}

/**
 * Implements hook_init().
 *
 * Include search JS for every pageload!
 */
function loop_external_sources_content_init() {
  global $user;

  // Check if it's a registered user.
  if ($user->uid > 0) {
    drupal_add_js(drupal_get_path('module', 'loop_external_sources_content') . '/js/search.js');
  }
}
