<?php

/**
 * Implements hook_install().
 *
 * Add user role.
 */
function loop_saml_install() {
  $role = new stdClass();
  $role->name = 'saml';
  // Save the role to the Drupal database.
  user_role_save($role);
}

/**
 * Implements hook_uninstall().
 *
 * Remove user role.
 */
function loop_saml_uninstall() {
  $role = user_role_load_by_name('saml');
  if ($role) {
    // Role found. Delete it.
    user_role_delete($role);
  }
}
