<?php
/**
 * @file
 * Code for the Loop user feature.
 */

include_once 'loop_user.features.inc';

/**
 * Implements hook_views_api().
 */
function loop_user_views_api() {
  return array('api' => 3.0);
}


/**
 * Implements hook_block_info().
 */
function loop_user_block_info() {
  // "My content" block.
  $blocks['loop_user_my_content'] = array(
    'info' => t('User my content'),
    'cache' => DRUPAL_CACHE_PER_PAGE,
  );
  return $blocks;
}


/**
 * Implements hook_block_view().
 */
function loop_user_block_view($delta = '') {
  $block = array();
  switch ($delta) {
    case 'loop_user_my_content':
      // "My content" block.
      if (user_access('access content')) {
        if (arg(0) == 'user' && is_numeric(arg(1))) {
          $profile = user_load(arg(1));
        }
        else {
          $profile = FALSE;
        }
        $variables = array('profile' => $profile);
        $block['content'] = theme('loop_user_my_content', $variables);
      }
      else {
        $block['content'] = FALSE;
      }
      break;
  }
  return $block;
}


/**
 * Implements hook_theme().
 */
function loop_user_theme() {
  return array(
    'loop_user_my_content' => array(
      'variables' => array(),
      'template' => 'templates/loop-user--my-content',
    ),
  );
}
