<?php
/**
 * @file
 * Code for the Loop External data feature.
 */

include_once 'loop_external_data.features.inc';


/*
 * Implements hook_file_insert().
 *
 * This function will check for correct content and forward ZIP content to our
 * parser that will figure out what internal parser is required.
 */
function loop_external_data_file_insert($file) {
  $a = 0;
  if (($file->filemime == 'application/zip') && (strstr($file->uri, 'index_file') !== TRUE)) {
    // We got a ZIP file and the correct CT is used for uploading.
    include 'parser.php';
    $parser = new Parser();
    $parser->parse(drupal_realpath($file->uri), drupal_realpath('public://index_file/' . $file->fid));
  }
}
