<nav class="nav-mobile js-mobile-nav">
  <a href="#" title="Min konto" class="nav-mobile--link">
    <span class="nav-mobile--text">Min konto</span>
  </a>
  <a href="#" title="Notifikationer" class="nav-mobile--link">
    <span class="nav-mobile--text">Notifikationer</span>
  </a>
  <a href="#" title="Menu" class="nav-mobile--link">
    <span class="nav-mobile--text">Menu</span>
  </a>
  <a href="#" title="Min konto" class="nav-mobile--link">
    <span class="nav-mobile--text">Min konto</span>
  </a>
  <a href="#" title="Notifikationer" class="nav-mobile--link">
    <span class="nav-mobile--text">Notifikationer</span>
  </a>
  <a href="#" title="Menu" class="nav-mobile--link">
    <span class="nav-mobile--text">Menu</span>
  </a>
  <a href="#" title="Min konto" class="nav-mobile--link">
    <span class="nav-mobile--text">Min konto</span>
  </a>
  <a href="#" title="Notifikationer" class="nav-mobile--link">
    <span class="nav-mobile--text">Notifikationer</span>
  </a>
  <a href="#" title="Menu" class="nav-mobile--link">
    <span class="nav-mobile--text">Menu</span>
  </a>
  <a href="#" title="Min konto" class="nav-mobile--link">
    <span class="nav-mobile--text">Min konto</span>
  </a>
  <a href="#" title="Notifikationer" class="nav-mobile--link">
    <span class="nav-mobile--text">Notifikationer</span>
  </a>
  <a href="#" title="Menu" class="nav-mobile--link">
    <span class="nav-mobile--text">Menu</span>
  </a>
  <a href="#" title="Min konto" class="nav-mobile--link">
    <span class="nav-mobile--text">Min konto</span>
  </a>
  <a href="#" title="Notifikationer" class="nav-mobile--link">
    <span class="nav-mobile--text">Notifikationer</span>
  </a>
  <a href="#" title="Menu" class="nav-mobile--link">
    <span class="nav-mobile--text">Menu</span>
  </a>
</nav>
<header class="header" role="banner">
  <div class="header--inner">
    <a href="/" class="logo--link"><img src="<?php echo $path_to_theme; ?>/logo.png" alt="" class="logo--image"></a>
    <nav class="nav">
      <a href="#" title="Min konto" class="nav--link">
        <img src="<?php echo $path_to_theme; ?>images/nav-user-icon.png" class="nav--icon">
        <span class="nav--text">Min konto</span>
      </a>
      <a href="#" title="Notifikationer" class="nav--link">
        <img src="<?php echo $path_to_theme; ?>images/nav-mail-icon.png" class="nav--icon">
        <span class="nav--text">Notifikationer</span>
        <span class="notification">3</span>
      </a>
      <a href="#" title="Menu" class="nav--link js-toggle-mobile-nav">
        <img src="<?php echo $path_to_theme; ?>images/nav-menu-icon.png" class="nav--icon">
        <span class="nav--text">Menu</span>
      </a>
    </nav>
  </div>
</header>