<!DOCTYPE html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <meta name="viewport" content="width=device-width">
  <link rel="stylesheet" href="/profiles/loopdk/themes/loop/css/styles.css">
  <link rel="stylesheet" href="/profiles/loopdk/themes/loop/icons/loop-icons.css">
  <script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/1.5.1/jquery.min.js"></script>
  <script type="text/javascript" src="/profiles/loopdk/themes/loop/scripts/mobile-nav.js"></script>