<nav class="nav-mobile js-mobile-nav">
  <a href="#" title="" class="first leaf nav-mobile--link active">
    <span class="nav-mobile--text">Example menu item</span>
  </a>
  <a href="#" title="" class="last leaf nav-mobile--link active">
    <span class="nav-mobile--text">Another example menu item</span>
  </a>
</nav>
<header class="header" role="banner">
  <div class="header--inner">
    <a href="/" class="logo--link"><img src="<?php echo $path_to_theme; ?>/logo.png" alt="" class="logo--image"></a>
    <nav class="nav">
      <a href="#" title="" class="first leaf nav--link">
        <img class="nav--icon" src="<?php echo $path_to_theme; ?>images/nav-user-icon.png">
        <span class="nav--text">My account</span>
      </a>
      <a href="#" title="" class="leaf nav--link">
        <img class="nav--icon" src="<?php echo $path_to_theme; ?>images/nav-mail-icon.png">
        <span class="nav--text">Messages</span>
      </a>
      <a href="#" title="" class="leaf nav--link">
        <img class="nav--icon" src="<?php echo $path_to_theme; ?>images/nav-add-icon.png">
        <span class="nav--text">Create post</span>
      </a>
      <a href="#" title="" class="last leaf nav--link js-toggle-mobile-nav nolink">
        <img class="nav--icon" src="<?php echo $path_to_theme; ?>images/nav-menu-icon.png">
        <span class="nav--text">Menu</span>
      </a>
    </nav>
  </div>
</header>
