<div class="layout-dashboard">
  <div class="layout--inner">
    <div class="layout-element-alpha">
    </div>
    <div class="layout-element-beta">
    </div>
  </div>
  <div class="layout--inner">
    <div class="layout-element-gamma">
      <h2 class="dashboard-list--header">Content (sorted by latest)</h2>
      <div class="dashboard-list--filter">
        <img src="https://cdn1.iconfinder.com/data/icons/windows8_icons/26/filled_filter.png" class="dashboard-list--filter-image">
        <input type="text" placeholder="Type text that is part of title or content to filter the list" class="dashboard-list--filter-field">
      </div>
      <div class="dashboard-list">
        <div class="dashboard-list--item">
          <a href="#" class="dashboard-list--icon"><img src="https://cdn2.iconfinder.com/data/icons/freecns-cumulus/16/519584-081_Pen-128.png"></a>
          <p class="dashboard-list--text"><a href="#">Hvordan dokumenteres delvis aktindsigt?</a></p>
        </div>
        <div class="dashboard-list--item">
          <a href="#" class="dashboard-list--icon"><img src="https://cdn2.iconfinder.com/data/icons/freecns-cumulus/16/519584-081_Pen-128.png"></a>
          <p class="dashboard-list--text"><a href="#">Hvordan er det nu jeg får lukket et forløb ned når jeg afslutter borger?</a></p>
        </div>
        <div class="dashboard-list--item">
          <a href="#" class="dashboard-list--icon"><img src="https://cdn2.iconfinder.com/data/icons/freecns-cumulus/16/519584-081_Pen-128.png"></a>
          <p class="dashboard-list--text"><a href="#">Hvordan dokumenteres delvis aktindsigt?</a></p>
        </div>
        <div class="dashboard-list--item">
          <a href="#" class="dashboard-list--icon"><img src="https://cdn2.iconfinder.com/data/icons/freecns-cumulus/16/519584-081_Pen-128.png"></a>
          <p class="dashboard-list--text"><a href="#">Hvordan er det nu jeg får lukket et forløb ned når jeg afslutter borger?</a></p>
        </div>
        <div class="dashboard-list--item">
          <a href="#" class="dashboard-list--icon"><img src="https://cdn2.iconfinder.com/data/icons/freecns-cumulus/16/519584-081_Pen-128.png"></a>
          <p class="dashboard-list--text"><a href="#">Hvordan dokumenteres delvis aktindsigt?</a></p>
        </div>
        <div class="dashboard-list--item">
          <a href="#" class="dashboard-list--icon"><img src="https://cdn2.iconfinder.com/data/icons/freecns-cumulus/16/519584-081_Pen-128.png"></a>
          <p class="dashboard-list--text"><a href="#">Hvordan er det nu jeg får lukket et forløb ned når jeg afslutter borger?</a></p>
        </div>
        <div class="dashboard-list--item">
          <a href="#" class="dashboard-list--icon"><img src="https://cdn2.iconfinder.com/data/icons/freecns-cumulus/16/519584-081_Pen-128.png"></a>
          <p class="dashboard-list--text"><a href="#">Hvordan dokumenteres delvis aktindsigt?</a></p>
        </div>
        <div class="dashboard-list--item">
          <a href="#" class="dashboard-list--icon"><img src="https://cdn2.iconfinder.com/data/icons/freecns-cumulus/16/519584-081_Pen-128.png"></a>
          <p class="dashboard-list--text"><a href="#">Hvordan er det nu jeg får lukket et forløb ned når jeg afslutter borger?</a></p>
        </div>
        <div class="dashboard-list--item">
          <a href="#" class="dashboard-list--icon"><img src="https://cdn2.iconfinder.com/data/icons/freecns-cumulus/16/519584-081_Pen-128.png"></a>
          <p class="dashboard-list--text"><a href="#">Hvordan dokumenteres delvis aktindsigt?</a></p>
        </div>
        <div class="dashboard-list--item">
          <a href="#" class="dashboard-list--icon"><img src="https://cdn2.iconfinder.com/data/icons/freecns-cumulus/16/519584-081_Pen-128.png"></a>
          <p class="dashboard-list--text"><a href="#">Hvordan er det nu jeg får lukket et forløb ned når jeg afslutter borger?</a></p>
        </div>
      </div>
    </div>
    <div class="layout-element-delta">
      <h2 class="dashboard-list--header">Users (sorted by latest)</h2>
      <div class="dashboard-list--filter">
        <img src="https://cdn1.iconfinder.com/data/icons/windows8_icons/26/filled_filter.png" class="dashboard-list--filter-image">
        <input type="text" placeholder="Type username or email to filter the list" class="dashboard-list--filter-field">
      </div>
      <div class="dashboard-list">
        <div class="dashboard-list--item">
          <div class="meta-data--author-image">
            <a href="/user/1"><img width="192" height="192" alt="" src="http://loop.etek.dk/sites/loop.etek.dk/files/styles/preview/public/default_images/default-user-icon_0.png?itok=nzsQFyyj"></a>
          </div>
          <a href="#" class="dashboard-list--icon"><img src="https://cdn2.iconfinder.com/data/icons/freecns-cumulus/16/519584-081_Pen-128.png"></a>
          <p class="dashboard-user-list--text"><a href="#">my@aarhus.dk</a> <span class="dashboard-list--info">(Martin Yde, Social- og sundhedshjælper)</span></p>
        </div>
        <div class="dashboard-list--item">
          <div class="meta-data--author-image">
            <a href="/user/1"><img width="192" height="192" alt="" src="http://loop.etek.dk/sites/loop.etek.dk/files/styles/preview/public/default_images/default-user-icon_0.png?itok=nzsQFyyj"></a>
          </div>
          <a href="#" class="dashboard-list--icon"><img src="https://cdn2.iconfinder.com/data/icons/freecns-cumulus/16/519584-081_Pen-128.png"></a>
          <p class="dashboard-user-list--text"><a href="#">azkb104</a> <span class="dashboard-list--info">(Bruger navn, Sygeplejerske)</span></p>
        </div>
        <div class="dashboard-list--item">
          <div class="meta-data--author-image">
            <a href="#">
              <img src="/sites/default/files/styles/profile/public/pictures/picture-36-1394707409.jpg?itok=GlUcivB4">
            </a>
          </div>
          <a href="#" class="dashboard-list--icon"><img src="https://cdn2.iconfinder.com/data/icons/freecns-cumulus/16/519584-081_Pen-128.png"></a>
          <p class="dashboard-user-list--text"><a href="#">azba399</a> <span class="dashboard-list--info">(Bruger navn, Sygeplejerske)</span></p>
        </div>
        <div class="dashboard-list--item">
          <div class="meta-data--author-image">
            <a href="/user/1"><img width="192" height="192" alt="" src="http://loop.etek.dk/sites/loop.etek.dk/files/styles/preview/public/default_images/default-user-icon_0.png?itok=nzsQFyyj"></a>
          </div>
          <a href="#" class="dashboard-list--icon"><img src="https://cdn2.iconfinder.com/data/icons/freecns-cumulus/16/519584-081_Pen-128.png"></a>
          <p class="dashboard-user-list--text"><a href="#">azmda50</a> <span class="dashboard-list--info">(Bruger navn, Sygeplejerske)</span></p>
        </div>
        <div class="dashboard-list--item">
          <div class="meta-data--author-image">
            <a href="/user/1"><img width="192" height="192" alt="" src="http://loop.etek.dk/sites/loop.etek.dk/files/styles/preview/public/default_images/default-user-icon_0.png?itok=nzsQFyyj"></a>
          </div>
          <a href="#" class="dashboard-list--icon"><img src="https://cdn2.iconfinder.com/data/icons/freecns-cumulus/16/519584-081_Pen-128.png"></a>
          <p class="dashboard-user-list--text"><a href="#">azmda42</a> <span class="dashboard-list--info">(Bruger navn, Sygeplejerske)</span></p>
        </div>
        <div class="dashboard-list--item">
          <div class="meta-data--author-image">
            <a href="/user/1"><img width="192" height="192" alt="" src="http://loop.etek.dk/sites/loop.etek.dk/files/styles/preview/public/default_images/default-user-icon_0.png?itok=nzsQFyyj"></a>
          </div>
          <a href="#" class="dashboard-list--icon"><img src="https://cdn2.iconfinder.com/data/icons/freecns-cumulus/16/519584-081_Pen-128.png"></a>
          <p class="dashboard-user-list--text"><a href="#">my@aarhus.dk</a> <span class="dashboard-list--info">(Bruger navn, Sygeplejerske)</span></p>
        </div>
        <div class="dashboard-list--item">
          <div class="meta-data--author-image">
            <a href="/user/1"><img width="192" height="192" alt="" src="http://loop.etek.dk/sites/loop.etek.dk/files/styles/preview/public/default_images/default-user-icon_0.png?itok=nzsQFyyj"></a>
          </div>
          <a href="#" class="dashboard-list--icon"><img src="https://cdn2.iconfinder.com/data/icons/freecns-cumulus/16/519584-081_Pen-128.png"></a>
          <p class="dashboard-user-list--text"><a href="#">azkb104</a> <span class="dashboard-list--info">(Bruger navn, Sygeplejerske)</span></p>
        </div>
        <div class="dashboard-list--item">
          <div class="meta-data--author-image">
            <a href="/user/1"><img width="192" height="192" alt="" src="http://loop.etek.dk/sites/loop.etek.dk/files/styles/preview/public/default_images/default-user-icon_0.png?itok=nzsQFyyj"></a>
          </div>
          <a href="#" class="dashboard-list--icon"><img src="https://cdn2.iconfinder.com/data/icons/freecns-cumulus/16/519584-081_Pen-128.png"></a>
          <p class="dashboard-user-list--text"><a href="#">azba399</a> <span class="dashboard-list--info">(Bruger navn, Sygeplejerske)</span></p>
        </div>
        <div class="dashboard-list--item">
          <div class="meta-data--author-image">
            <a href="/user/1"><img width="192" height="192" alt="" src="http://loop.etek.dk/sites/loop.etek.dk/files/styles/preview/public/default_images/default-user-icon_0.png?itok=nzsQFyyj"></a>
          </div>
          <a href="#" class="dashboard-list--icon"><img src="https://cdn2.iconfinder.com/data/icons/freecns-cumulus/16/519584-081_Pen-128.png"></a>
          <p class="dashboard-user-list--text"><a href="#">azmda50</a> <span class="dashboard-list--info">(Bruger navn, Sygeplejerske)</span></p>
        </div>
        <div class="dashboard-list--item">
          <div class="meta-data--author-image">
            <a href="/user/1"><img width="192" height="192" alt="" src="http://loop.etek.dk/sites/loop.etek.dk/files/styles/preview/public/default_images/default-user-icon_0.png?itok=nzsQFyyj"></a>
          </div>
          <a href="#" class="dashboard-list--icon"><img src="https://cdn2.iconfinder.com/data/icons/freecns-cumulus/16/519584-081_Pen-128.png"></a>
          <p class="dashboard-user-list--text"><a href="#">azmda42</a> <span class="dashboard-list--info">(Bruger navn, Sygeplejerske)</span></p>
        </div>
      </div>
    </div>
  </div>
</div>
