<div class="layout-dashboard">
  <div class="layout--inner">
    <div class="layout-element-alpha">
    </div>
    <div class="layout-element-beta">
    </div>
  </div>
  <div class="layout--inner">
    <div class="layout-element-gamma">
      <h2 class="dashboard-list--header">Latest users</h2>
      <div class="dashboard-list">
        <div class="dashboard-list--item">
          <p class="dashboard-list--text"><a href="#">my@aarhus.dk</a></p>
        </div>
        <div class="dashboard-list--item">
          <p class="dashboard-list--text"><a href="#">azkb104</a></p>
        </div>
        <div class="dashboard-list--item">
          <p class="dashboard-list--text"><a href="#">azba399</a></p>
        </div>
        <div class="dashboard-list--item">
          <p class="dashboard-list--text"><a href="#">azmda50</a></p>
        </div>
        <div class="dashboard-list--item">
          <p class="dashboard-list--text"><a href="#">azmda42</a></p>
        </div>
      </div>
    </div>
    <div class="layout-element-delta">
    </div>
  </div>
</div>
