<div class="panel-pane pane-block pane-search-form loop-frontpage--search-block search-block">
  <div class="panel-pane--inner">
    <div class="pane-content">
      <form action="/" method="post" id="search-block-form" accept-charset="UTF-8">
        <div>
          <div class="search--field-wrapper">
            <div class="form-item form-type-searchfield form-item-search-block-form">
              <label for="edit-search-block-form--2">Search for an answer</label>
              <span class="field-prefix"><i class="search--icon icon-search"></i></span>
              <input title="Indtast de ord du ønsker at søge efter." placeholder="Indtast de ord du ønsker at søge efter." class="search--field form-text form-search" type="search" id="edit-search-block-form--2" name="search_block_form" value="" size="15" maxlength="128">
            </div>
            <div class="form-actions form-wrapper" id="edit-actions">
              <input class="search--button form-submit" type="submit" id="edit-submit" name="op" value="Søg">
            </div>
          </div>
        </div>
      </form>
    </div>
  </div>
</div>
