<aside class="block-user-links">
  <div class="block-module--inner">
    <h2 class="block-module--user-links-header">Min konto</h2>
    <ul class="block-module--user-links-list">
      <li class="block-module--user-links-item active"><a href="#">Min profil</a></li>
      <li class="block-module--user-links-item"><a href="#">Redigér profil</a></li>
      <li class="block-module--user-links-item"><a href="#">Skift kodeord</a></li>
      <li class="block-module--user-links-item"><a href="#">Notifikationer</a></li>
      <li class="block-module--user-links-item"><a href="#">Abonnementer</a></li>
      <li class="block-module--user-links-item"><a href="#">Log ud</a></li>
    </ul>
  </div>
</aside>
