<aside class="block-my-content">
  <div class="block-module--inner">
    <h2 class="block-module--my-content-header">Mit indhold</h2>
    <ul class="block-module--my-content-list">
      <li class="block-module--my-content-item"><a href="" class="block-module--link">Mine spørgsmål</a></li>
      <li class="block-module--my-content-item"><a href="" class="block-module--link">Mine kommentarer</a></li>
    </ul>
  </div>
</aside>
