<aside class="block-follow-question">
  <div class="block-module--inner">
    <h2 class="block-module--header">Følg spørgsmål</h2>
    <div class="block-module--content">Du følger dette spørgsmål og får tilsendt en e-mail når der kommer nye svar.</div>
    <div class="flag-outer flag-outer-subscribe-node">
      <span class="flag-wrapper flag-subscribe-node flag-subscribe-node-24 node--flag-wrapper">
        <a rel="nofollow" class="flag unflag-action flag-link-toggle node--flag flag-processed" title="" href="#">Unsubscribe</a>
      </span>
    </div>
  </div>
</aside>
