<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
  <meta name="viewport" content="width=device-width" />
  <link rel="stylesheet" href="/modules/system/system.base.css" media="all" />
  <link rel="stylesheet" href="/modules/comment/comment.css" media="all" />
  <link rel="stylesheet" href="/modules/field/theme/field.css" media="all" />
  <link rel="stylesheet" href="/modules/node/node.css" media="all" />
  <link rel="stylesheet" href="/modules/search/search.css" media="all" />
  <link rel="stylesheet" href="/modules/user/user.css" media="all" />
  <link rel="stylesheet" href="/profiles/loop/modules/contrib/views/css/views.css" media="all" />
  <link rel="stylesheet" href="/profiles/loop/modules/contrib/ctools/css/ctools.css" media="all" />
  <link rel="stylesheet" href="/profiles/loop/modules/contrib/panels/css/panels.css" media="all" />
  <link rel="stylesheet" href="/profiles/loop/modules/contrib/panels/plugins/layouts/onecol/onecol.css" media="all" />
  <link rel="stylesheet" href="/profiles/loop/themes/loop/css/styles.css" media="all" />
  <link rel="stylesheet" href="/profiles/loop/themes/loop/icons/loop-icons.css" media="all" />
  <!--[if IE 8]>
  <link rel="stylesheet" href="/profiles/loop/themes/loop/css/ie8.css" />
  <![endif]-->
  <!--[if lt IE 10]>
  <link rel="stylesheet" href="/profiles/loop/themes/loop/css/lt-ie10.css" />
  <![endif]-->

  <script src="/profiles/loop/themes/loop/scripts/modernizr.js"></script>
  <script src="/profiles/loop/libraries/respondjs/respond.min.js"></script>
  <script src="/profiles/loop/modules/contrib/jquery_update/replace/jquery/1.9/jquery.min.js?v=1.9.1"></script>
  <script src="/misc/jquery.once.js?v=1.2"></script>
  <script src="/misc/drupal.js"></script>
  <script src="/profiles/loop/modules/features/loop_search/handlebars-v1.2.0.js"></script>
  <script src="/profiles/loop/modules/features/loop_search/typeahead.bundle.js"></script>
  <script src="/profiles/loop/modules/features/loop_search/loop_search.js"></script>
  <script src="/profiles/loop/modules/contrib/panels/js/panels.js"></script>
  <script src="/profiles/loop/themes/loop/scripts/mobile-nav.js"></script>
