<div class="layout-default">
  <div class="layout--inner">
    <div class="layout-element-alpha">
      <section class="question--wrapper">
        <div class="meta-data--author">
          <div class="meta-data--author-image">
            <a href="#">
              <img src="https://s3.amazonaws.com/uifaces/faces/twitter/jackiesaik/128.jpg">
            </a>
          </div>
          <div class="meta-data--author-wrapper">
            <a href="#" class="meta-data--author-link">Ribena Hutsitove</a>
            <span class="meta-data--author-title">SOSU, AUH, HUH</span>
          </div>
        </div>
        <div class="question--meta-data">
          <div class="question--meta-data-date">Oprettet den 27. februar 2013</div>
          <span class="question--meta-data-category">Kategori:</span> <a href="#">Dokumentationspraksis</a>
        </div>
        <div class="question--inner">
          <span class="question--label">Spørgsmål:</span>
          <h1 class="question">Hvordan dokumenteres delvis aktindsigt? Og findes der en vejledning i dokumentation af aktindsigt?</h1>
        </div>
        <div class="question--terms">
          <a href="#" class="question--term">Stamdata</a>
          <a href="#" class="question--term">Partsrepræsentant</a>
          <a href="#" class="question--term">Funktionsvurdering</a>
        </div>
      </section>
      <div class="comments--comment is-sticky">
        <div class="meta-data--author">
          <div class="meta-data--author-image">
            <a href="#">
              <img src="https://s3.amazonaws.com/uifaces/faces/twitter/jackiesaik/128.jpg">
            </a>
          </div>
          <div class="meta-data--author-wrapper">
            <a href="#" class="meta-data--author-link">Ribena Hutsitove</a>
            <span class="meta-data--author-title">SOSU, AUH, HUH</span>
          </div>
        </div>
        <a href="#" class="comment--flag is-sticky">Mest nyttige svar</a>
        <span class="comments--comment-meta-data">Oprettet den 28. marts 2013</span>
        <div class="comments--comment-content">
          <p>Nej der er ikke en selvstændig vejledning i aktindsigt. Under aktindsigt (i Stamdata) kan Status sættes til Delvis bevilliget samt i bemærkningen kan dokumenteres hvilken sag det omfatter.</p>
        </div>
      </div>
      <div class="comments--comment">
        <div class="meta-data--author">
          <div class="meta-data--author-image">
            <a href="#">
              <img src="https://s3.amazonaws.com/uifaces/faces/twitter/jackiesaik/128.jpg">
            </a>
          </div>
          <div class="meta-data--author-wrapper">
            <a href="#" class="meta-data--author-link">Ribena Hutsitove</a>
            <span class="meta-data--author-title">SOSU, AUH, HUH</span>
          </div>
        </div>
        <span class="comments--comment-meta-data">Oprettet den 28. marts 2013</span>
        <div class="comments--comment-content">
          <p>Nej der er ikke en selvstændig vejledning i aktindsigt. Under aktindsigt (i Stamdata) kan Status sættes til Delvis bevilliget samt i bemærkningen kan dokumenteres hvilken sag det omfatter.</p>
        </div>
        <a href="#" class="comment--flag">Dette svar er nyttigt (12)</a>
      </div>
      <div class="comments--comment">
        <div class="meta-data--author">
          <div class="meta-data--author-image">
            <a href="#">
              <img src="https://s3.amazonaws.com/uifaces/faces/twitter/jackiesaik/128.jpg">
            </a>
          </div>
          <div class="meta-data--author-wrapper">
            <a href="#" class="meta-data--author-link">Ribena Hutsitove</a>
            <span class="meta-data--author-title">SOSU, AUH, HUH</span>
          </div>
        </div>
        <span class="comments--comment-meta-data">Oprettet den 28. marts 2013</span>
        <div class="comments--comment-content">
          <p>Nej der er ikke en selvstændig vejledning i aktindsigt. Under aktindsigt (i Stamdata) kan Status sættes til Delvis bevilliget samt i bemærkningen kan dokumenteres hvilken sag det omfatter.</p>
        </div>
        <a href="#" class="comment--flag">Dette svar er nyttigt (0)</a>
      </div>
      <div class="comments--comment">
        <div class="meta-data--author">
          <div class="meta-data--author-image">
            <a href="#">
              <img src="https://s3.amazonaws.com/uifaces/faces/twitter/jackiesaik/128.jpg">
            </a>
          </div>
          <div class="meta-data--author-wrapper">
            <a href="#" class="meta-data--author-link">Ribena Hutsitove</a>
            <span class="meta-data--author-title">SOSU, AUH, HUH</span>
          </div>
        </div>
        <span class="comments--comment-meta-data">Oprettet den 28. marts 2013</span>
        <div class="comments--comment-content">
          <p>Nej der er ikke en selvstændig vejledning i aktindsigt. Under aktindsigt (i Stamdata) kan Status sættes til Delvis bevilliget samt i bemærkningen kan dokumenteres hvilken sag det omfatter.</p>
        </div>
        <a href="#" class="comment--flag is-active">Du fandt dette svar nyttigt</a>
      </div>
      <div class="comments--comment">
        <div class="meta-data--author">
          <div class="meta-data--author-image">
            <a href="#">
              <img src="https://s3.amazonaws.com/uifaces/faces/twitter/jackiesaik/128.jpg">
            </a>
          </div>
          <div class="meta-data--author-wrapper">
            <a href="#" class="meta-data--author-link">Ribena Hutsitove</a>
            <span class="meta-data--author-title">SOSU, AUH, HUH</span>
          </div>
        </div>
        <span class="comments--comment-meta-data">Oprettet den 28. marts 2013</span>
        <div class="comments--comment-content">
          <p>Nej der er ikke en selvstændig vejledning i aktindsigt. Under aktindsigt (i Stamdata) kan Status sættes til Delvis bevilliget samt i bemærkningen kan dokumenteres hvilken sag det omfatter.</p>
        </div>
        <a href="#" class="comment--flag">Dette svar er nyttigt (3)</a>
      </div>
    </div>
    <div class="layout-element-beta">
      <?php include 'inc/block-follow-question.inc'; ?>
      <?php include 'inc/block-unfollow-question.inc'; ?>
    </div>
  </div>
  <div class="layout--inner">
    <div class="layout-element-gamma">
      <div class="meta-data--author">
        <div class="meta-data--author-image">
          <a href="#">
            <img src="https://s3.amazonaws.com/uifaces/faces/twitter/jackiesaik/128.jpg">
          </a>
        </div>
        <div class="meta-data--author-wrapper">
          Ribena Hutsitove
          <span class="meta-data--author-title">SOSU, AUH, HUH</span>
        </div>
      </div>
      <div class="form-module">
        <form action="ask-question.php">
          <div class="form-item form-type-textarea">
            <label for="comment-textarea">Skriv svar <span class="form-required">*</span></label>
            <textarea rows="5" class="form-textarea required" id="comment-textarea"></textarea>
          </div>
          <div class="form-actions">
            <input type="submit" value="Skriv svar" class="form-submit">
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
