<div class="layout-dashboard">
  <div class="layout--inner">
    <div class="layout-element-alpha">
      <h2 class="dashboard-list--header">Questions (sorted by latest)</h2>
      <div class="dashboard-list--filter">
        <input type="text" placeholder="Type text that is part of title or content to filter the list" class="dashboard-list--filter-field">
      </div>
      <div class="dashboard-list">
        <div class="dashboard-list--item">
          <a href="#" class="dashboard-list--icon"></a>
          <p class="dashboard-list--text"><a href="#">Hvordan dokumenteres delvis aktindsigt?</a></p>
          <span class="dashboard-list--meta-data">Spørgsmål, oprettet den 28. marts 2013</span>
        </div>
        <div class="dashboard-list--item">
          <a href="#" class="dashboard-list--icon"></a>
          <p class="dashboard-list--text"><a href="#">Hvordan er det nu jeg får lukket et forløb ned når jeg afslutter borger?</a></p>
          <span class="dashboard-list--meta-data">Spørgsmål, oprettet den 28. marts 2013</span>
        </div>
        <div class="dashboard-list--item">
          <a href="#" class="dashboard-list--icon"></a>
          <p class="dashboard-list--text"><a href="#">Hvordan dokumenteres delvis aktindsigt?</a></p>
          <span class="dashboard-list--meta-data">Spørgsmål, oprettet den 28. marts 2013</span>
        </div>
        <div class="dashboard-list--item">
          <a href="#" class="dashboard-list--icon"></a>
          <p class="dashboard-list--text"><a href="#">Hvordan er det nu jeg får lukket et forløb ned når jeg afslutter borger?</a></p>
          <span class="dashboard-list--meta-data">Spørgsmål, oprettet den 28. marts 2013</span>
        </div>
        <div class="dashboard-list--item">
          <a href="#" class="dashboard-list--icon"></a>
          <p class="dashboard-list--text"><a href="#">Hvordan dokumenteres delvis aktindsigt?</a></p>
          <span class="dashboard-list--meta-data">Spørgsmål, oprettet den 28. marts 2013</span>
        </div>
        <div class="dashboard-list--item">
          <a href="#" class="dashboard-list--icon"></a>
          <p class="dashboard-list--text"><a href="#">Hvordan er det nu jeg får lukket et forløb ned når jeg afslutter borger?</a></p>
          <span class="dashboard-list--meta-data">Spørgsmål, oprettet den 28. marts 2013</span>
        </div>
        <div class="dashboard-list--item">
          <a href="#" class="dashboard-list--icon"></a>
          <p class="dashboard-list--text"><a href="#">Hvordan dokumenteres delvis aktindsigt?</a></p>
          <span class="dashboard-list--meta-data">Spørgsmål, oprettet den 28. marts 2013</span>
        </div>
        <div class="dashboard-list--item">
          <a href="#" class="dashboard-list--icon"></a>
          <p class="dashboard-list--text"><a href="#">Hvordan er det nu jeg får lukket et forløb ned når jeg afslutter borger?</a></p>
          <span class="dashboard-list--meta-data">Spørgsmål, oprettet den 28. marts 2013</span>
        </div>
        <div class="dashboard-list--item">
          <a href="#" class="dashboard-list--icon"></a>
          <p class="dashboard-list--text"><a href="#">Hvordan dokumenteres delvis aktindsigt?</a></p>
          <span class="dashboard-list--meta-data">Spørgsmål, oprettet den 28. marts 2013</span>
        </div>
        <div class="dashboard-list--item">
          <a href="#" class="dashboard-list--icon"></a>
          <p class="dashboard-list--text"><a href="#">Hvordan er det nu jeg får lukket et forløb ned når jeg afslutter borger?</a></p>
          <span class="dashboard-list--meta-data">Spørgsmål, oprettet den 28. marts 2013</span>
        </div>
      </div>
    </div>
    <div class="layout-element-beta">
      <h2 class="dashboard-list--header">Other content (sorted by latest)</h2>
      <div class="dashboard-list--filter">
        <input type="text" placeholder="Type text that is part of title or content to filter the list" class="dashboard-list--filter-field">
      </div>
      <div class="dashboard-list">
        <div class="dashboard-list--item">
          <a href="#" class="dashboard-list--icon"></a>
          <p class="dashboard-list--text"><a href="#">Hvordan dokumenteres delvis aktindsigt?</a></p>
          <span class="dashboard-list--meta-data">Side, oprettet den 28. marts 2013</span>
        </div>
        <div class="dashboard-list--item">
          <a href="#" class="dashboard-list--icon"></a>
          <p class="dashboard-list--text"><a href="#">Hvordan er det nu jeg får lukket et forløb ned når jeg afslutter borger?</a></p>
          <span class="dashboard-list--meta-data">Side, oprettet den 28. marts 2013</span>
        </div>
        <div class="dashboard-list--item">
          <a href="#" class="dashboard-list--icon"></a>
          <p class="dashboard-list--text"><a href="#">Hvordan dokumenteres delvis aktindsigt?</a></p>
          <span class="dashboard-list--meta-data">Side, oprettet den 28. marts 2013</span>
        </div>
        <div class="dashboard-list--item">
          <a href="#" class="dashboard-list--icon"></a>
          <p class="dashboard-list--text"><a href="#">Hvordan er det nu jeg får lukket et forløb ned når jeg afslutter borger?</a></p>
          <span class="dashboard-list--meta-data">Side, oprettet den 28. marts 2013</span>
        </div>
        <div class="dashboard-list--item">
          <a href="#" class="dashboard-list--icon"></a>
          <p class="dashboard-list--text"><a href="#">Hvordan dokumenteres delvis aktindsigt?</a></p>
          <span class="dashboard-list--meta-data">Side, oprettet den 28. marts 2013</span>
        </div>
        <div class="dashboard-list--item">
          <a href="#" class="dashboard-list--icon"></a>
          <p class="dashboard-list--text"><a href="#">Hvordan er det nu jeg får lukket et forløb ned når jeg afslutter borger?</a></p>
          <span class="dashboard-list--meta-data">Side, oprettet den 28. marts 2013</span>
        </div>
        <div class="dashboard-list--item">
          <a href="#" class="dashboard-list--icon"></a>
          <p class="dashboard-list--text"><a href="#">Hvordan dokumenteres delvis aktindsigt?</a></p>
          <span class="dashboard-list--meta-data">Side, oprettet den 28. marts 2013</span>
        </div>
        <div class="dashboard-list--item">
          <a href="#" class="dashboard-list--icon"></a>
          <p class="dashboard-list--text"><a href="#">Hvordan er det nu jeg får lukket et forløb ned når jeg afslutter borger?</a></p>
          <span class="dashboard-list--meta-data">Side, oprettet den 28. marts 2013</span>
        </div>
        <div class="dashboard-list--item">
          <a href="#" class="dashboard-list--icon"></a>
          <p class="dashboard-list--text"><a href="#">Hvordan dokumenteres delvis aktindsigt?</a></p>
          <span class="dashboard-list--meta-data">Side, oprettet den 28. marts 2013</span>
        </div>
        <div class="dashboard-list--item">
          <a href="#" class="dashboard-list--icon"></a>
          <p class="dashboard-list--text"><a href="#">Hvordan er det nu jeg får lukket et forløb ned når jeg afslutter borger?</a></p>
          <span class="dashboard-list--meta-data">Side, oprettet den 28. marts 2013</span>
        </div>
      </div>
    </div>
  </div>
  <div class="layout--inner">
    <div class="layout-element-gamma">
      <h2 class="dashboard-list--header">Comments (sorted by latest)</h2>
      <div class="dashboard-list--filter">
        <input type="text" placeholder="Type text that is part of title or content to filter the list" class="dashboard-list--filter-field">
      </div>
      <div class="dashboard-list">
        <div class="dashboard-image-list--item">
          <div class="meta-data--author-image">
            <a href="/user/1"><img width="192" height="192" alt="" src="/sites/default/files/styles/profile/public/pictures/picture-6-1392707743.png?itok=oT7mVmo-"></a>
          </div>
          <a href="#" class="dashboard-list--icon"></a>
          <p class="dashboard-list--text">
            <a href="#">Hvordan dokumenteres delvis aktindsigt?</a>
            <span class="dashboard-list--meta-data">Spørgsmål, oprettet den 28. marts 2013</span>
          </p>
        </div>
        <div class="dashboard-image-list--item">
          <div class="meta-data--author-image">
            <a href="/user/1"><img width="192" height="192" alt="" src="/sites/default/files/styles/profile/public/pictures/picture-6-1392707743.png?itok=oT7mVmo-"></a>
          </div>
          <a href="#" class="dashboard-list--icon"></a>
          <p class="dashboard-list--text">
            <a href="#">Hvordan dokumenteres delvis aktindsigt?</a>
            <span class="dashboard-list--meta-data">Spørgsmål, oprettet den 28. marts 2013</span>
          </p>
        </div>
        <div class="dashboard-image-list--item">
          <div class="meta-data--author-image">
            <a href="/user/1"><img width="192" height="192" alt="" src="/sites/default/files/styles/profile/public/pictures/picture-6-1392707743.png?itok=oT7mVmo-"></a>
          </div>
          <a href="#" class="dashboard-list--icon"></a>
          <p class="dashboard-list--text">
            <a href="#">Hvordan dokumenteres delvis aktindsigt?</a>
            <span class="dashboard-list--meta-data">Spørgsmål, oprettet den 28. marts 2013</span>
          </p>
        </div>
        <div class="dashboard-image-list--item">
          <div class="meta-data--author-image">
            <a href="/user/1"><img width="192" height="192" alt="" src="/sites/default/files/styles/profile/public/pictures/picture-6-1392707743.png?itok=oT7mVmo-"></a>
          </div>
          <a href="#" class="dashboard-list--icon"></a>
          <p class="dashboard-list--text">
            <a href="#">Hvordan dokumenteres delvis aktindsigt?</a>
            <span class="dashboard-list--meta-data">Spørgsmål, oprettet den 28. marts 2013</span>
          </p>
        </div>
        <div class="dashboard-image-list--item">
          <div class="meta-data--author-image">
            <a href="/user/1"><img width="192" height="192" alt="" src="/sites/default/files/styles/profile/public/pictures/picture-6-1392707743.png?itok=oT7mVmo-"></a>
          </div>
          <a href="#" class="dashboard-list--icon"></a>
          <p class="dashboard-list--text">
            <a href="#">Hvordan dokumenteres delvis aktindsigt?</a>
            <span class="dashboard-list--meta-data">Spørgsmål, oprettet den 28. marts 2013</span>
          </p>
        </div>
        <div class="dashboard-image-list--item">
          <div class="meta-data--author-image">
            <a href="/user/1"><img width="192" height="192" alt="" src="/sites/default/files/styles/profile/public/pictures/picture-6-1392707743.png?itok=oT7mVmo-"></a>
          </div>
          <a href="#" class="dashboard-list--icon"></a>
          <p class="dashboard-list--text">
            <a href="#">Hvordan dokumenteres delvis aktindsigt?</a>
            <span class="dashboard-list--meta-data">Spørgsmål, oprettet den 28. marts 2013</span>
          </p>
        </div>
        <div class="dashboard-image-list--item">
          <div class="meta-data--author-image">
            <a href="/user/1"><img width="192" height="192" alt="" src="/sites/default/files/styles/profile/public/pictures/picture-6-1392707743.png?itok=oT7mVmo-"></a>
          </div>
          <a href="#" class="dashboard-list--icon"></a>
          <p class="dashboard-list--text">
            <a href="#">Hvordan dokumenteres delvis aktindsigt?</a>
            <span class="dashboard-list--meta-data">Spørgsmål, oprettet den 28. marts 2013</span>
          </p>
        </div>
        <div class="dashboard-image-list--item">
          <div class="meta-data--author-image">
            <a href="/user/1"><img width="192" height="192" alt="" src="/sites/default/files/styles/profile/public/pictures/picture-6-1392707743.png?itok=oT7mVmo-"></a>
          </div>
          <a href="#" class="dashboard-list--icon"></a>
          <p class="dashboard-list--text">
            <a href="#">Hvordan dokumenteres delvis aktindsigt?</a>
            <span class="dashboard-list--meta-data">Spørgsmål, oprettet den 28. marts 2013</span>
          </p>
        </div>
        <div class="dashboard-image-list--item">
          <div class="meta-data--author-image">
            <a href="/user/1"><img width="192" height="192" alt="" src="/sites/default/files/styles/profile/public/pictures/picture-6-1392707743.png?itok=oT7mVmo-"></a>
          </div>
          <a href="#" class="dashboard-list--icon"></a>
          <p class="dashboard-list--text">
            <a href="#">Hvordan dokumenteres delvis aktindsigt?</a>
            <span class="dashboard-list--meta-data">Spørgsmål, oprettet den 28. marts 2013</span>
          </p>
        </div>
        <div class="dashboard-image-list--item">
          <div class="meta-data--author-image">
            <a href="/user/1"><img width="192" height="192" alt="" src="/sites/default/files/styles/profile/public/pictures/picture-6-1392707743.png?itok=oT7mVmo-"></a>
          </div>
          <a href="#" class="dashboard-list--icon"></a>
          <p class="dashboard-list--text">
            <a href="#">Hvordan dokumenteres delvis aktindsigt?</a>
            <span class="dashboard-list--meta-data">Spørgsmål, oprettet den 28. marts 2013</span>
          </p>
        </div>
      </div>
    </div>
    <div class="layout-element-delta">
      <h2 class="dashboard-list--header">Users (sorted by latest)</h2>
      <div class="dashboard-list--filter">
        <input type="text" placeholder="Type username or email to filter the list" class="dashboard-list--filter-field">
      </div>
      <div class="dashboard-list">
        <div class="dashboard-image-list--item">
          <div class="meta-data--author-image">
            <a href="/user/1"><img width="192" height="192" alt="" src="/sites/default/files/styles/profile/public/pictures/picture-6-1392707743.png?itok=oT7mVmo-"></a>
          </div>
          <a href="#" class="dashboard-list--icon"></a>
          <p class="dashboard-list--text">
            <a href="#">azmda50</a>
            <span class="dashboard-list--meta-data">Bruger navn, Sygeplejerske</span>
          </p>
        </div>
        <div class="dashboard-image-list--item">
          <div class="meta-data--author-image">
            <a href="/user/1"><img width="192" height="192" alt="" src="/sites/default/files/styles/profile/public/pictures/picture-6-1392707743.png?itok=oT7mVmo-"></a>
          </div>
          <a href="#" class="dashboard-list--icon"></a>
          <p class="dashboard-list--text">
            <a href="#">azmda50</a>
            <span class="dashboard-list--meta-data">Bruger navn, Sygeplejerske</span>
          </p>
        </div>
        <div class="dashboard-image-list--item">
          <div class="meta-data--author-image">
            <a href="#">
              <a href="/user/1"><img width="192" height="192" alt="" src="/sites/default/files/styles/profile/public/pictures/picture-6-1392707743.png?itok=oT7mVmo-"></a>
            </a>
          </div>
          <a href="#" class="dashboard-list--icon"></a>
          <p class="dashboard-list--text">
            <a href="#">azmda50</a>
            <span class="dashboard-list--meta-data">Bruger navn, Sygeplejerske</span>
          </p>
        </div>
        <div class="dashboard-image-list--item">
          <div class="meta-data--author-image">
            <a href="/user/1"><img width="192" height="192" alt="" src="/sites/default/files/styles/profile/public/pictures/picture-6-1392707743.png?itok=oT7mVmo-"></a>
          </div>
          <a href="#" class="dashboard-list--icon"></a>
          <p class="dashboard-list--text">
            <a href="#">azmda50</a>
            <span class="dashboard-list--meta-data">Bruger navn, Sygeplejerske</span>
          </p>
        </div>
        <div class="dashboard-image-list--item">
          <div class="meta-data--author-image">
            <a href="/user/1"><img width="192" height="192" alt="" src="/sites/default/files/styles/profile/public/pictures/picture-6-1392707743.png?itok=oT7mVmo-"></a>
          </div>
          <a href="#" class="dashboard-list--icon"></a>
          <p class="dashboard-list--text">
            <a href="#">azmda50</a>
            <span class="dashboard-list--meta-data">Bruger navn, Sygeplejerske</span>
          </p>
        </div>
        <div class="dashboard-image-list--item">
          <div class="meta-data--author-image">
            <a href="/user/1"><img width="192" height="192" alt="" src="/sites/default/files/styles/profile/public/pictures/picture-6-1392707743.png?itok=oT7mVmo-"></a>
          </div>
          <a href="#" class="dashboard-list--icon"></a>
          <p class="dashboard-list--text">
            <a href="#">azmda50</a>
            <span class="dashboard-list--meta-data">Bruger navn, Sygeplejerske</span>
          </p>
        </div>
        <div class="dashboard-image-list--item">
          <div class="meta-data--author-image">
            <a href="/user/1"><img width="192" height="192" alt="" src="/sites/default/files/styles/profile/public/pictures/picture-6-1392707743.png?itok=oT7mVmo-"></a>
          </div>
          <a href="#" class="dashboard-list--icon"></a>
          <p class="dashboard-list--text">
            <a href="#">azmda50</a>
            <span class="dashboard-list--meta-data">Bruger navn, Sygeplejerske</span>
          </p>
        </div>
        <div class="dashboard-image-list--item">
          <div class="meta-data--author-image">
            <a href="/user/1"><img width="192" height="192" alt="" src="/sites/default/files/styles/profile/public/pictures/picture-6-1392707743.png?itok=oT7mVmo-"></a>
          </div>
          <a href="#" class="dashboard-list--icon"></a>
          <p class="dashboard-list--text">
            <a href="#">azmda50</a>
            <span class="dashboard-list--meta-data">Bruger navn, Sygeplejerske</span>
          </p>
        </div>
        <div class="dashboard-image-list--item">
          <div class="meta-data--author-image">
            <a href="/user/1"><img width="192" height="192" alt="" src="/sites/default/files/styles/profile/public/pictures/picture-6-1392707743.png?itok=oT7mVmo-"></a>
          </div>
          <a href="#" class="dashboard-list--icon"></a>
          <p class="dashboard-list--text">
            <a href="#">azmda50</a>
            <span class="dashboard-list--meta-data">Bruger navn, Sygeplejerske</span>
          </p>
        </div>
        <div class="dashboard-image-list--item">
          <div class="meta-data--author-image">
            <a href="/user/1"><img width="192" height="192" alt="" src="/sites/default/files/styles/profile/public/pictures/picture-6-1392707743.png?itok=oT7mVmo-"></a>
          </div>
          <a href="#" class="dashboard-list--icon"></a>
          <p class="dashboard-list--text">
            <a href="#">azmda50</a>
            <span class="dashboard-list--meta-data">Bruger navn, Sygeplejerske</span>
          </p>
        </div>
      </div>
    </div>
  </div>
</div>
