<div class="layout-frontpage">
  <div class="layout--inner">
    <div class="layout-element-alpha">
      <h2 class="notification--list-header">Du har <span class="notification--inline">5</span> notifikationer</h2>
      <div class="view view-user-messages view-id-user_messages view-display-id-panel_pane_1 view-dom-id-8f8717ae42781cb1588efa399709ebd4 jquery-once-1-processed" data-new-message-count="1">
        <div class="view-content">
          <div class="notification--list-item">
            <span class="flag-wrapper flag-message-read flag-message-read-55 message--flag-wrapper">
              <a rel="nofollow" class="flag flag-action flag-link-toggle message--flag flag-processed" title="" href="#">Mark as read</a>
            </span>
            <p class="notification--list-text">Nyt svar på spørgsmålet "<a href="#">Hvordan dokumenteres delvis aktindsigt?</a>"</p>
          </div>
          <div class="notification--list-item">
            <span class="flag-wrapper flag-message-read flag-message-read-55 message--flag-wrapper">
              <a rel="nofollow" class="flag flag-action flag-link-toggle message--flag flag-processed" title="" href="#">Mark as read</a>
            </span>
            <p class="notification--list-text">Nyt svar på spørgsmålet "<a href="#">Skal der tilføjes prosa i Funktionsvurderingen, hvis borger under et punkt scorer 1 eller 4?</a>"</p>
          </div>
          <div class="notification--list-item">
            <span class="flag-wrapper flag-message-read flag-message-read-55 message--flag-wrapper">
              <a rel="nofollow" class="flag flag-action flag-link-toggle message--flag flag-processed" title="" href="#">Mark as read</a>
            </span>
            <p class="notification--list-text">Nyt svar på spørgsmålet "<a href="#">Hvordan finder jeg oplysninger på samarbejdspartnere i jounalen fx BK</a>"</p>
          </div>
          <div class="notification--list-item">
            <span class="flag-wrapper flag-message-read flag-message-read-55 message--flag-wrapper">
              <a rel="nofollow" class="flag flag-action flag-link-toggle message--flag flag-processed" title="" href="#">Mark as read</a>
            </span>
            <p class="notification--list-text">Nyt svar på spørgsmålet "<a href="#">Hvordan dokumenteres delvis aktindsigt?</a>"</p>
          </div>
          <div class="notification--list-item">
            <span class="flag-wrapper flag-message-read flag-message-read-55 message--flag-wrapper">
              <a rel="nofollow" class="flag flag-action flag-link-toggle message--flag flag-processed" title="" href="#">Mark as read</a>
            </span>
            <p class="notification--list-text">Nyt svar på spørgsmålet "<a href="#">Hvordan dokumenteres delvis aktindsigt?</a>"</p>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="layout--inner">
    <div class="layout-element-beta">
      <div class="block-questions--wrapper">
        <div class="block-questions--header-wrapper">
          <h2 class="block-questions--header">Hjælp en kollega!</h2>
          <h4 class="block-questions--sub-header">Spørgsmål indenfor: <em>Ledelse</em></h4>
        </div>
        <div class="block-questions--list">
          <div class="block-questions--item">
            <div class="meta-data--author">
              <div class="meta-data--author-image">
                <a href="#">
                  <img src="/sites/default/files/styles/profile/public/pictures/picture-6-1392707743.png?itok=oT7mVmo-">
                </a>
              </div>
              <div class="meta-data--author-wrapper">
                <a href="#" class="meta-data--author-link">Ribena Hutsitove</a>
                <span class="meta-data--author-title">SOSU, AUH, HUH</span>
              </div>
            </div>
            <span class="meta-data--date">Oprettet den 28. marts 2013</span>
            <a href="question.php" class="block-questions--link">Hvordan dokumenteres delvis aktindsigt? Og findes der en vejledning i dokumentation af aktindsigt?</a>
          </div>
          <div class="block-questions--item">
            <div class="meta-data--author">
              <div class="meta-data--author-image">
                <a href="#">
                  <img src="/sites/default/files/styles/profile/public/pictures/picture-6-1392707743.png?itok=oT7mVmo-">
                </a>
              </div>
              <div class="meta-data--author-wrapper">
                <a href="#" class="meta-data--author-link">Ribena Hutsitove</a>
                <span class="meta-data--author-title">SOSU, AUH, HUH</span>
              </div>
            </div>
            <span class="meta-data--date">Oprettet den 28. marts 2013</span>
            <a href="question.php" class="search-result--link">Hvordan dokumenteres delvis aktindsigt?</a>
          </div>
          <div class="search-result--item">
            <div class="meta-data--author">
              <div class="meta-data--author-image">
                <a href="#">
                  <img src="/sites/default/files/styles/profile/public/pictures/picture-36-1394707409.jpg?itok=GlUcivB4">
                </a>
              </div>
              <div class="meta-data--author-wrapper">
                <a href="#" class="meta-data--author-link">Ribena Hutsitove</a>
                <span class="meta-data--author-title">SOSU, AUH, HUH</span>
              </div>
            </div>
            <span class="meta-data--date">Oprettet den 28. marts 2013</span>
            <a href="question.php" class="search-result--link">Hvordan finder jeg oplysninger på samarbejdspartnere i jounalen fx BK</a>
          </div>
          <div class="search-result--item">
            <div class="meta-data--author">
              <div class="meta-data--author-image">
                <a href="#">
                  <img src="/sites/default/files/styles/profile/public/pictures/picture-6-1392707743.png?itok=oT7mVmo-">
                </a>
              </div>
              <div class="meta-data--author-wrapper">
                <a href="#" class="meta-data--author-link">Ribena Hutsitove</a>
                <span class="meta-data--author-title">SOSU, AUH, HUH</span>
              </div>
            </div>
            <span class="meta-data--date">Oprettet den 28. marts 2013</span>
            <a href="question.php" class="search-result--link">Skal der tilføjes prosa i Funktionsvurderingen, hvis borger under et punkt scorer 1 eller 4?</a>
          </div>
          <div class="search-result--item">
            <div class="meta-data--author">
              <div class="meta-data--author-image">
                <a href="#">
                  <img src="/sites/default/files/styles/profile/public/pictures/picture-36-1394707409.jpg?itok=GlUcivB4">
                </a>
              </div>
              <div class="meta-data--author-wrapper">
                <a href="#" class="meta-data--author-link">Ribena Hutsitove</a>
                <span class="meta-data--author-title">SOSU, AUH, HUH</span>
              </div>
            </div>
            <span class="meta-data--date">Oprettet den 28. marts 2013</span>
            <a href="question.php" class="search-result--link">Skal der tilføjes prosa i Funktionsvurderingen, hvis borger under et punkt scorer 1 eller 4?</a>
          </div>
        </div>
      </div>
    </div>
    <div class="layout-element-gamma">
      <div class="block-questions--wrapper">
        <div class="block-questions--header-wrapper">
          <h2 class="block-questions--header">Du er eksperten! Kan du hjælpe?</h2>
          <h4 class="block-questions--sub-header">Spørgsmål indenfor: <em>Funktionsvurdering</em>, <em>Medicin</em>, <em>Planlægning (Booking, Disponering)</em></h4>
        </div>
        <div class="block-questions--list">
          <div class="block-questions--item">
            <div class="meta-data--author">
              <div class="meta-data--author-image">
                <a href="#">
                  <img src="/sites/default/files/styles/profile/public/pictures/picture-6-1392707743.png?itok=oT7mVmo-">
                </a>
              </div>
              <div class="meta-data--author-wrapper">
                <a href="#" class="meta-data--author-link">Ribena Hutsitove</a>
                <span class="meta-data--author-title">SOSU, AUH, HUH</span>
              </div>
            </div>
            <span class="meta-data--date">Oprettet den 28. marts 2013</span>
            <a href="question.php" class="block-questions--link">Hvordan dokumenteres delvis aktindsigt? Og findes der en vejledning i dokumentation af aktindsigt?</a>
          </div>
          <div class="search-result--item">
            <div class="meta-data--author">
              <div class="meta-data--author-image">
                <a href="#">
                  <img src="/sites/default/files/styles/profile/public/pictures/picture-6-1392707743.png?itok=oT7mVmo-">
                </a>
              </div>
              <div class="meta-data--author-wrapper">
                <a href="#" class="meta-data--author-link">Ribena Hutsitove</a>
                <span class="meta-data--author-title">SOSU, AUH, HUH</span>
              </div>
            </div>
            <span class="meta-data--date">Oprettet den 28. marts 2013</span>
            <a href="question.php" class="search-result--link">Hvordan dokumenteres delvis aktindsigt?</a>
          </div>
          <div class="search-result--item">
            <div class="meta-data--author">
              <div class="meta-data--author-image">
                <a href="#">
                  <img src="/sites/default/files/styles/profile/public/pictures/picture-36-1394707409.jpg?itok=GlUcivB4">
                </a>
              </div>
              <div class="meta-data--author-wrapper">
                <a href="#" class="meta-data--author-link">Ribena Hutsitove</a>
                <span class="meta-data--author-title">SOSU, AUH, HUH</span>
              </div>
            </div>
            <span class="meta-data--date">Oprettet den 28. marts 2013</span>
            <a href="question.php" class="search-result--link">Hvordan finder jeg oplysninger på samarbejdspartnere i jounalen fx BK</a>
          </div>
          <div class="search-result--item">
            <div class="meta-data--author">
              <div class="meta-data--author-image">
                <a href="#">
                  <img src="/sites/default/files/styles/profile/public/pictures/picture-6-1392707743.png?itok=oT7mVmo-">
                </a>
              </div>
              <div class="meta-data--author-wrapper">
                <a href="#" class="meta-data--author-link">Ribena Hutsitove</a>
                <span class="meta-data--author-title">SOSU, AUH, HUH</span>
              </div>
            </div>
            <span class="meta-data--date">Oprettet den 28. marts 2013</span>
            <a href="question.php" class="search-result--link">Skal der tilføjes prosa i Funktionsvurderingen, hvis borger under et punkt scorer 1 eller 4?</a>
          </div>
          <div class="search-result--item">
            <div class="meta-data--author">
              <div class="meta-data--author-image">
                <a href="#">
                  <img src="/sites/default/files/styles/profile/public/pictures/picture-36-1394707409.jpg?itok=GlUcivB4">
                </a>
              </div>
              <div class="meta-data--author-wrapper">
                <a href="#" class="meta-data--author-link">Ribena Hutsitove</a>
                <span class="meta-data--author-title">SOSU, AUH, HUH</span>
              </div>
            </div>
            <span class="meta-data--date">Oprettet den 28. marts 2013</span>
            <a href="question.php" class="search-result--link">Skal der tilføjes prosa i Funktionsvurderingen, hvis borger under et punkt scorer 1 eller 4?</a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
