<?php
$path_to_theme = "/profiles/loop/themes/loop/";
?>
<div class="typeahead-block">
  <form>
    <div class="typeahead-block--wrapper">
      <label for="typeahead">Search for an answer</label>
      <i class="typeahead-block--icon"></i>
      <input type="text" id="typeahead" title="E.g. &quot;How do you document a subject&quot;" placeholder="E.g. &quot;How do you document a subject&quot;" class="typeahead tt-query" style="position: relative; vertical-align: top; background-color: transparent;">
      <input type="submit" value="Search" class="typeahead-block--button">
    </div>
  </form>
</div>
