<div class="layout-default-inverted">
  <div class="layout--inner">
    <div class="layout-element-alpha">
      <?php include('inc/block-user-links.inc') ?>
      <?php include('inc/block-my-content.inc') ?>
    </div>
    <div class="layout-element-beta">
      <h1>Lars Larsen <span class="user-profile-module--edit-link">(<a href="/user/1/edit">redigér</a>)</span></h1>
      <fieldset class="user-profile-module--field-group-fieldset-personal-info">
        <legend class="fieldset-legend">Personlige informationer</legend>
        <div class="user-profile-module--personal-info-text">
          <div class="user-profile-module--field-personal-info">
            <span class="user-profile-module--field-label">Fornavn:</span><span class="user-profile-module--field-value">Lars</span>
          </div>
          <div class="user-profile-module--field-personal-info">
            <span class="user-profile-module--field-label">Efternavn:</span><span class="user-profile-module--field-value">Larsen</span>
          </div>
          <div class="user-profile-module--field-personal-info">
            <span class="user-profile-module--field-label">Email:</span><span class="user-profile-module--field-value">lars@larsen.dk</span>
          </div>
        </div>
        <div class="user-profile-module--personal-info-image">
          <img src="http://placekitten.com/120/120"/>
        <div>
      </fieldset>
      <fieldset class="user-profile-module--field-group-fieldset">
        <legend class="fieldset-legend">Jobtitel</legend>
        <div class="user-profile-module--field">
          Administrativ medarbejder
        </div>
      </fieldset>
      <fieldset class="user-profile-module--field-group-fieldset">
        <legend class="fieldset-legend">Profession</legend>
        <div class="user-profile-module--field">
          Sosu-hjælper
        </div>
      </fieldset>
      <fieldset class="user-profile-module--field-group-fieldset">
        <legend class="fieldset-legend">Lokation</legend>
        ITK</br>
        Møllegade 1</br>
        8000 Aarhus C</br>
      </fieldset>
      <fieldset class="user-profile-module--field-group-fieldset">
        <legend class="fieldset-legend">Beskrivelse</legend>
        <div class="user-profile-module--field">
          Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt
        </div>
      </fieldset>
    </div>
  </div>
</div>