<?php

/**
 * @file loop_permissions.module.
 * Module file for secure role/permissions in code.
 */

include_once 'loop_permissions.features.inc';

/**
 * @file Secure Permissions Data
 * Module file for secure permissions in code.
 */

/**
 * Implements hook_permissions().
 *
 * Add permission to restrict access to certain admin paths.
 */
function loop_permissions_permission() {
  $permissions = array();

  $paths = array(
    'admin',
    'admin/content',
    'admin/content/abuse',
    'admin/content/abuse/*',
  );

  foreach ($paths as $path) {
    $permissions['access path ' . $path] = array(
      'title' => t('Access path %path', array('%path' => $path)),
      'description' => t('Access path %path', array('%path' => $path)),
    );
  }

  return $permissions;
}

/**
 * Implements hook_menu_alter().
 *
 * See http://stackoverflow.com/a/5125994.
 */
function loop_permissions_menu_alter(&$items) {
  foreach ($items as $path => &$item) {
    if ($path === 'admin' || strpos($path, 'admin/') === 0) {
      if (isset($item['access arguments'])) {
        $item['access arguments'][] = isset($item['access callback']) ? $item['access callback'] : 'user_access';
      }
      else {
        $item['access arguments'] = array();
      }
      $item['access arguments'][] = $path;
      $item['access callback'] = 'loop_permissions_menu_access';
    }
  }
}

/**
 * Menu access callback.
 */
function loop_permissions_menu_access() {
  $args = func_get_args();
  $path = array_pop($args);
  $access_callback = array_pop($args);

  if (is_callable($access_callback) && count($args) > 0 && !call_user_func_array($access_callback, $args)) {
    return FALSE;
  }

  // Non "administrator" users must have explicit access to admin paths.
  $user_role_names = array_values($GLOBALS['user']->roles);
  if (!array_intersect($user_role_names, array('administrator'))) {
    if (!user_access('access path ' . $path)) {
      // Check path to see if any wild card permission matches.
      while ($path = preg_replace('@/?[^/]+$@', '', $path)) {
        if (user_access('access path ' . $path . '/*')) {
          return TRUE;
        }
      }

      return FALSE;
    }
  }

  return TRUE;
}


/**
 * Define site roles in code.
 *
 * Create a secure_permissions_data module directory and place this function
 * in secure_permissions_data.module.
 *
 * @return
 *   An array defining all the roles for the site.
 */
function loop_permissions_secure_permissions_roles() {
  return array(
    'anonymous user',
    'read only',
    'authenticated user',
    'administrator',
    'documentation coordinator',
    'manager',
    'external sources editor',
  );
}

/**
 * Define site permissions in code.
 *
 * Create a secure_permissions_data module directory and place this function
 * in secure_permissions_data.module.
 *
 * @param $role
 *   The role for which the permissions are being requested.
 *
 * @return
 *   An array defining all the permissions for the site.
 */
function loop_permissions_secure_permissions($role) {
  $permissions = array(
    'authenticated user' => array(
      'access comments',
      'access content',
      'access search_api_page',
      'access statistics',
      'access user profiles',
      'create messages',
      'create post content',
      'edit own comments',
      'edit own post content',
      'flag message_read',
      'flag ranking',
      'flag subscribe_node',
      'flag subscribe_term',
      'flag subscribe_taxonomy',
      'post comments',
      'Report abuse',
      'search content',
      'send complaints on comments',
      'skip comment approval',
      'unflag message_read',
      'unflag ranking',
      'unflag subscribe_node',
      'unflag subscribe_term',
      'unflag subscribe_taxonomy',
      'use Rules component rules_remove_subscription',
      'use text format simple',
      'view own unpublished content',
      'view post access counter',
    ),
    'administrator' => array(
      'access administration pages',
      'access all views',
      'access content overview',
      'access contextual links',
      'access own authorizations',
      'access own consumers',
      'access rules debug',
      'access site in maintenance mode',
      'access site reports',
      'access statistics',
      'access toolbar',
      'access user profiles',
      'Administer abuse reports',
      'Administer all abuse reports',
      'administer actions',
      'administer advanced pane settings',
      'Administer all abuse reports',
      'administer blocks',
      'administer comments',
      'administer complaints',
      'administer consumers',
      'administer content types',
      'administer facets',
      'administer features',
      'administer fieldgroups',
      'administer filters',
      'administer flags',
      'administer google analytics',
      'administer google analytics counter',
      'administer image styles',
      'administer languages',
      'administer mailsystem',
      'administer menu',
      'administer message subscribe',
      'administer message types',
      'administer meta tags',
      'administer module filter',
      'administer modules',
      'administer nodes',
      'administer oauth',
      'administer page manager',
      'administer page titles',
      'administer pane access',
      'administer panels layouts',
      'administer panels styles',
      'administer pathauto',
      'administer pcp',
      'administer permissions',
      'administer redirects',
      'administer rules',
      'administer search_api',
      'Administer short URLs',
      'administer site configuration',
      'administer software updates',
      'administer statistics',
      'administer taxonomy',
      'administer themes',
      'administer url aliases',
      'administer users',
      'administer uuid',
      'administer views',
      'block IP addresses',
      'bypass node access',
      'bypass rules access',
      'cancel account',
      'change layouts in place editing',
      'change own username',
      'create external_sources content',
      'create page content',
      'Create short URLs',
      'create url aliases',
      'delete any external_sources content',
      'delete any page content',
      'delete any post content',
      'delete own external_sources content',
      'delete own page content',
      'delete own post content',
      'Delete own URLs',
      'delete revisions',
      'delete terms in 1',
      'delete terms in 2',
      'delete terms in 3',
      'edit any external_sources content',
      'edit any page content',
      'edit any post content',
      'edit meta tags',
      'edit mimemail user settings',
      'edit own external_sources content',
      'edit own page content',
      'edit terms in 1',
      'edit terms in 2',
      'edit terms in 3',
      'Enter custom URLs',
      'export secure permissions',
      'generate features',
      'manage features',
      'manage Shorten URLs API keys',
      'notify of path changes',
      'oauth authorize any consumers',
      'oauth register any consumers',
      'opt-in or out of tracking',
      'revert revisions',
      'select account cancellation method',
      'send arbitrary files',
      'set page title',
      'set revision date for content',
      'show format selection for comment',
      'show format selection for flagging',
      'show format selection for message',
      'show format selection for message_type',
      'show format selection for message_type_category',
      'show format selection for node',
      'show format selection for rules_config',
      'show format selection for taxonomy_term',
      'show format selection for user',
      'show format tips',
      'show more format tips link',
      'translate admin strings',
      'translate interface',
      'translate user-defined strings',
      'use flag import',
      'use page manager',
      'use panels caching features',
      'use panels dashboard',
      'use panels in place editing',
      'use panels locks',
      'use PHP for label patterns',
      'use PHP for tracking visibility',
      'use Shorten URLs page',
      'use text format editor',
      'View own URL stats',
      'view pane admin links',
      'view revisions',
      'view the administration theme',
    ),
    'documentation coordinator' => array(
      'access user profiles',
      'Administer abuse reports',
      'Administer all abuse reports',
      'access path admin/content/abuse',
      'access path admin/content/abuse/*',
      'administer comments',
      'administer complaints',
      'administer nodes',
      'delete any post content',
      'delete own post content',
      'delete revisions',
      'delete terms in 1',
      'edit any post content',
      'edit terms in 1',
      'revert revisions',
      'set revision date for content',
      'use text format editor',
      'view revisions',
      'view the administration theme',
    ),
    'manager' => array(
      'access administration pages',
      'access contextual links',
      'access user profiles',
      'Administer abuse reports',
      'Administer all abuse reports',
      'access path admin/content/abuse',
      'access path admin/content/abuse/*',
      'administer taxonomy',
      'administer comments',
      'administer complaints',
      'administer menu-loop-primary-menu menu items',
      'administer nodes',
      'administer users',
      'assign documentation coordinator role',
      'assign manager role',
      'assign read only role',
      'create external_sources content',
      'create index content',
      'create page content',
      'Create short URLs',
      'create url aliases',
      'delete any external_sources content',
      'delete any index content',
      'delete any page content',
      'delete any post content',
      'delete own external_sources content',
      'delete own index content',
      'delete own page content',
      'delete own post content',
      'Delete own URLs',
      'delete terms in 1',
      'delete terms in 2',
      'delete terms in 3',
      'edit any external_sources content',
      'edit any index content',
      'edit any page content',
      'edit any post content',
      'edit own external_sources content',
      'edit own index content',
      'edit own page content',
      'edit terms in 1',
      'edit terms in 2',
      'edit terms in 3',
      'Enter custom URLs',
      'manage Shorten URLs API keys',
      'set revision date for content',
      'translate admin strings',
      'translate interface',
      'translate user-defined strings',
      'use Shorten URLs page',
      'use text format editor',
      'View own URL stats',
      'view the administration theme',
    ),
    'external sources editor' => array(
      'access administration pages',
      // Allow access to some admin paths.
      'access path admin',
      'access path admin/content',

      'access content overview',
      'view the administration theme',
      'create external_sources content',
      'delete any external_sources content',
      'delete own external_sources content',
      'edit any external_sources content',
      'edit own external_sources content',
    ),
  );
  if (isset($permissions[$role])) {
    return $permissions[$role];
  }
}