<?php
/**
 * @file
 * Adds support for SAML integration via SimpleSAMLphp.
 */

/**
 * Return the SAML attribute to map to a given user profile field.
 * @param $field_name
 * @return string
 */
function loop_simplesamlphp_get_attribute_for_field($field_name) {
  $default_attribute_mapping = loop_simplesamlphp_get_default_mapping();
  return variable_get('loop_simplesamlphp_' . $field_name,
    $default_attribute_mapping[$field_name]);
}

/**
 * Return the default mapping between profile fields and SAML attributes.
 * @param string $field_name Optionally, the field name to retrieve the
 * default mapping for.
 * @return array
 */
function loop_simplesamlphp_get_default_mapping($field_name = NULL) {
  $defaults = array(
    'field_first_name' => 'gn',
    'field_last_name' => 'sn',
    'field_phone_number' => 'telephoneNumber',
    'field_job_title' => 'title',
    'field_location_place' => 'physicalDeliveryOfficeName',
    'field_location_address' => 'streetAddress',
    'field_location_postal_code' => 'postalCode',
    'field_location_city' => 'l',
  );
  if ($field_name === NULL) {
    return $defaults;
  }
  else {
    return $defaults[$field_name];
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Add settings for mapping SAML attributes to Loop user profile fields
 * to the simplesamlphp_auth configuration form located at
 * /admin/config/people/simplesamlphp_auth.
 */
function loop_simplesamlphp_form_simplesamlphp_auth_settings_alter(&$form, &$form_state, $form_id) {
  $loop_fieldset = array(
    '#type' => 'fieldset',
    '#title' => t('Loop User Attribute Mapping'),
    '#collapsible' => TRUE,
    '#collapsed' => FALSE
  );

  $loop_fieldset['loop_simplesamlphp_field_first_name'] = array(
    '#type' => 'textfield',
    '#title' => t('Which attribute from simpleSAMLphp should be used as user first name'),
    '#default_value' =>
      loop_simplesamlphp_get_attribute_for_field('field_first_name'),
    '#description' => t('Example: <i>@example</i><br />If the user attribute is multivalued, the first
 value will be used.', array(
      '@example' =>
        loop_simplesamlphp_get_default_mapping('field_first_name')
    )),
  );

  $loop_fieldset['loop_simplesamlphp_field_last_name'] = array(
    '#type' => 'textfield',
    '#title' => t('Which attribute from simpleSAMLphp should be used as user last name'),
    '#default_value' =>
      loop_simplesamlphp_get_attribute_for_field('field_last_name'),
    '#description' => t('Example: <i>@example</i><br />If the user attribute is multivalued, the first
 value will be used.', array(
      '@example' =>
        loop_simplesamlphp_get_default_mapping('field_last_name')
    )),
  );

  $loop_fieldset['loop_simplesamlphp_field_phone_number'] = array(
    '#type' => 'textfield',
    '#title' => t('Which attribute from simpleSAMLphp should be used as user phone number'),
    '#default_value' =>
      loop_simplesamlphp_get_attribute_for_field('field_phone_number'),
    '#description' => t('Example: <i>@example</i><br />If the user attribute is multivalued, the first
 value will be used.', array(
      '@example' =>
        loop_simplesamlphp_get_default_mapping('field_phone_number')
    )),
  );

  $loop_fieldset['loop_simplesamlphp_field_job_title'] = array(
    '#type' => 'textfield',
    '#title' => t('Which attribute from simpleSAMLphp should be used as user job title'),
    '#default_value' =>
      loop_simplesamlphp_get_attribute_for_field('field_job_title'),
    '#description' => t('Example: <i>@example</i><br />If the user attribute is multivalued, the first
 value will be used.', array(
      '@example' =>
        loop_simplesamlphp_get_default_mapping('field_job_title')
    )),
  );

  $loop_fieldset['loop_simplesamlphp_field_location_place'] = array(
    '#type' => 'textfield',
    '#title' => t('Which attribute from simpleSAMLphp should be used as user location'),
    '#default_value' =>
      loop_simplesamlphp_get_attribute_for_field('field_location_place'),
    '#description' => t('Example: <i>@example</i><br />If the user attribute is multivalued, the first
 value will be used.', array(
      '@example' =>
        loop_simplesamlphp_get_default_mapping('field_location_place')
    )),
  );

  $loop_fieldset['loop_simplesamlphp_field_location_address'] = array(
    '#type' => 'textfield',
    '#title' => t('Which attribute from simpleSAMLphp should be used as user address'),
    '#default_value' =>
      loop_simplesamlphp_get_attribute_for_field('field_location_address'),
    '#description' => t('Example: <i>@example</i><br />If the user attribute is multivalued, the first
 value will be used.', array(
      '@example' =>
        loop_simplesamlphp_get_default_mapping('field_location_address')
    )),
  );

  $loop_fieldset['loop_simplesamlphp_field_location_postal_code'] = array(
    '#type' => 'textfield',
    '#title' => t('Which attribute from simpleSAMLphp should be used as user postal code'),
    '#default_value' =>
      loop_simplesamlphp_get_attribute_for_field('field_location_postal_code'),
    '#description' => t('Example: <i>@example</i><br />If the user attribute is multivalued, the first
 value will be used.', array(
      '@example' =>
        loop_simplesamlphp_get_default_mapping('field_location_postal_code')
    )),
  );

  $loop_fieldset['loop_simplesamlphp_field_location_city'] = array(
    '#type' => 'textfield',
    '#title' => t('Which attribute from simpleSAMLphp should be used as user city'),
    '#default_value' =>
      loop_simplesamlphp_get_attribute_for_field('field_location_city'),
    '#description' => t('Example: <i>@example</i><br />If the user attribute is multivalued, the first
 value will be used.', array(
      '@example' =>
        loop_simplesamlphp_get_default_mapping('field_location_city')
    )),
  );


  $form['loop_simplesamlphp_user_attribute_mapping'] = $loop_fieldset;
}

/**
 * Implements hook_user_login().
 *
 * Updates the user's Loop account details.
 */
function loop_simplesamlphp_user_login(&$edit, $account) {
  $attributes = simplesamlphp_auth_get_attributes();
  if (!empty($attributes)) {
    $default_attribute_mapping = loop_simplesamlphp_get_default_mapping();
    // Loop through each attribute that we are trying to map
    foreach (array_keys($default_attribute_mapping) as $field_name) {
      // Get the attribute name to map to this field
      $attribute = loop_simplesamlphp_get_attribute_for_field($field_name);
      // Get the value of the SAML attribute
      $value = simplesamlphp_auth_get_attributes($attribute);
      if ($value !== NULL && isset($value[0])) {
        // Set the value on the user profile field
        $edit[$field_name][LANGUAGE_NONE][0]['value'] = $value[0];
      }
    }
    // Save the changes to the user profile
    user_save($account, $edit);
  }
}

/**
 * Implements hook_init().
 */
function loop_simplesamlphp_init() {
  // Do not run this from CLI.
  if (php_sapi_name() != 'cli') {
    if (user_is_anonymous() && !in_array($_GET['q'], array(
        'saml_login',
        'user/logout',
        'user/login'
      ))
    ) {
      // Redirect anonymous users to the saml login page
      drupal_goto('saml_login', array('query' => array('ReturnTo' => url($_GET['q'], array('absolute' => TRUE)))));
    }
  }
}

/**
 * Implements hook_preprocess().
 *
 * We wish to hide the logout link.
 */
function loop_simplesamlphp_preprocess(&$variables) {
  $variables['hide_logout'] = TRUE;
}
