<?php
/**
 * @file
 * loop_taxonomy_terms.features.uuid_term.inc
 */

/**
 * Implements hook_uuid_features_default_terms().
 */
function loop_taxonomy_terms_uuid_features_default_terms() {
  $terms = array();

  $terms[] = array(
    'name' => 'Postkasse',
    'description' => '',
    'format' => 'editor',
    'weight' => 0,
    'uuid' => '00a8b49d-27c9-4ece-a392-473c9e0b82da',
    'vocabulary_machine_name' => 'keyword',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Evaluering',
    'description' => '',
    'format' => 'editor',
    'weight' => 0,
    'uuid' => '04c82f8b-8c61-4b00-b148-48da05e2047c',
    'vocabulary_machine_name' => 'keyword',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Pn medicin',
    'description' => '',
    'format' => 'editor',
    'weight' => 0,
    'uuid' => '08b2aee2-9476-40b3-848a-6c5465d5f826',
    'vocabulary_machine_name' => 'keyword',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Kvittering',
    'description' => '',
    'format' => 'editor',
    'weight' => 0,
    'uuid' => '0d1b7d69-0e97-41ea-9eb3-0ee4b8e8a424',
    'vocabulary_machine_name' => 'keyword',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'UTH',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '1039a9fd-e53f-4094-a87b-d92d25f6b592',
    'vocabulary_machine_name' => 'keyword',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Brev',
    'description' => '',
    'format' => 'editor',
    'weight' => 0,
    'uuid' => '167c8380-0460-46a0-9774-4f13b4ce4410',
    'vocabulary_machine_name' => 'keyword',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Lokationsnummer',
    'description' => '',
    'format' => 'editor',
    'weight' => 0,
    'uuid' => '169b8bf3-fff7-4225-a22b-9ff6be94de1c',
    'vocabulary_machine_name' => 'keyword',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Terminal erklæring',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '1b6298d8-6aa0-49ff-968a-0326f19c1074',
    'vocabulary_machine_name' => 'keyword',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Husassistent',
    'description' => '',
    'format' => 'editor',
    'weight' => 10,
    'uuid' => '21915d62-61f7-40ab-9ada-b50debfdfc78',
    'vocabulary_machine_name' => 'profession',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'agtindsigt',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '26ba1c86-d4a9-470b-89af-d11e6b3dce98',
    'vocabulary_machine_name' => 'keyword',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'delvis aktindsigt',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '29b36031-58bb-4e63-a4c9-dca794ffa8ae',
    'vocabulary_machine_name' => 'keyword',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Disponering',
    'description' => '',
    'format' => 'editor',
    'weight' => 0,
    'uuid' => '2c633d54-f2c7-4432-947d-22aa85cdf0da',
    'vocabulary_machine_name' => 'keyword',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Leder',
    'description' => '',
    'format' => 'editor',
    'weight' => 13,
    'uuid' => '322d0ec1-b072-4425-9e9c-abd65e72711d',
    'vocabulary_machine_name' => 'profession',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Samlede faglig vurdering',
    'description' => '',
    'format' => 'editor',
    'weight' => 0,
    'uuid' => '332ea309-b950-4e96-a53c-f3f6d7a0e87b',
    'vocabulary_machine_name' => 'keyword',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Dokumentation',
    'description' => '',
    'format' => 'editor',
    'weight' => 0,
    'uuid' => '33b615c6-ede2-4399-9ffd-dd0f89125f5e',
    'vocabulary_machine_name' => 'subject',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Udskrivningsrapport',
    'description' => '',
    'format' => 'editor',
    'weight' => 0,
    'uuid' => '3668f114-9d6c-4913-9ed4-21e1424aeb4d',
    'vocabulary_machine_name' => 'keyword',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Teknisk servicemedarbejder/pedel/håndværker',
    'description' => '',
    'format' => 'editor',
    'weight' => 16,
    'uuid' => '374fc3b1-7193-4d02-838d-3d3069e3128a',
    'vocabulary_machine_name' => 'profession',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Forløb & Genoptræning',
    'description' => '',
    'format' => 'editor',
    'weight' => 0,
    'uuid' => '37e14251-9914-4b40-9d63-92a17b2b223b',
    'vocabulary_machine_name' => 'subject',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Forebyggende',
    'description' => '',
    'format' => 'editor',
    'weight' => 0,
    'uuid' => '3a784690-21d6-4cea-97f1-6ca9ffc042ba',
    'vocabulary_machine_name' => 'subject',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Standarder',
    'description' => '',
    'format' => 'editor',
    'weight' => 0,
    'uuid' => '3b037294-f202-4385-a3ee-8741d06569e7',
    'vocabulary_machine_name' => 'keyword',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Sagsark',
    'description' => '',
    'format' => 'editor',
    'weight' => 0,
    'uuid' => '3b6f6559-9e03-418d-aa45-550882b4b877',
    'vocabulary_machine_name' => 'keyword',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'journal',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '3c434e38-f716-4d91-9c24-c326aceb1b99',
    'vocabulary_machine_name' => 'keyword',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'erklæringer',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '3ea512fa-7658-46bd-86ea-9cc22d06d0eb',
    'vocabulary_machine_name' => 'keyword',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Overblik',
    'description' => '',
    'format' => 'editor',
    'weight' => 0,
    'uuid' => '40b043a8-94c1-47b2-a7ef-4d280c8bcaae',
    'vocabulary_machine_name' => 'keyword',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Funktionsvurdering',
    'description' => '',
    'format' => 'editor',
    'weight' => 0,
    'uuid' => '455d2316-963b-4a2b-a44f-8429da813cd5',
    'vocabulary_machine_name' => 'subject',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'IGVH',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '48b52f45-50c7-4456-8799-30b29e8d8a36',
    'vocabulary_machine_name' => 'keyword',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'aktindsigt',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '4937d50c-5561-498e-b6cd-f84339be7dd9',
    'vocabulary_machine_name' => 'keyword',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Medicin',
    'description' => '',
    'format' => 'editor',
    'weight' => 0,
    'uuid' => '4ea3aae3-3af2-4bc1-9c7b-b3d4b1c25aeb',
    'vocabulary_machine_name' => 'subject',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Visitator/Borgerkonsulent',
    'description' => '',
    'format' => 'editor',
    'weight' => 17,
    'uuid' => '551a13f2-5cf9-4a72-adc6-4cce2d569862',
    'vocabulary_machine_name' => 'profession',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Funktionsvurdering',
    'description' => '',
    'format' => 'editor',
    'weight' => 0,
    'uuid' => '570f08ac-4f2a-4f8c-bf9c-84ce843e7b43',
    'vocabulary_machine_name' => 'keyword',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Automatisk advis',
    'description' => '',
    'format' => 'editor',
    'weight' => 0,
    'uuid' => '590c342e-541e-477c-b558-a845b87a79ed',
    'vocabulary_machine_name' => 'keyword',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Fysioterapeut',
    'description' => '',
    'format' => 'editor',
    'weight' => -11,
    'uuid' => '593bde07-09d9-4e1c-b6f9-7b13b54df37d',
    'vocabulary_machine_name' => 'profession',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Stillingsbetegnelse',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '5987036c-ca34-49b9-bb7d-b134f4ccd084',
    'vocabulary_machine_name' => 'keyword',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'GOP',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '5a10f0d4-1af5-4b2e-804a-403c5514cf87',
    'vocabulary_machine_name' => 'keyword',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Køreliste',
    'description' => '',
    'format' => 'editor',
    'weight' => 0,
    'uuid' => '5dd88123-c9b8-48d3-8d28-1e10ae17ba54',
    'vocabulary_machine_name' => 'keyword',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Ydelser',
    'description' => '',
    'format' => 'editor',
    'weight' => 0,
    'uuid' => '62753e40-8b05-4cd4-9548-a5ef12f9a2b8',
    'vocabulary_machine_name' => 'keyword',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Korrespondance',
    'description' => '',
    'format' => 'editor',
    'weight' => 0,
    'uuid' => '64c7d28d-da0c-48a5-95c4-2761089b0835',
    'vocabulary_machine_name' => 'keyword',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Sygehjælper',
    'description' => '',
    'format' => 'editor',
    'weight' => 0,
    'uuid' => '64e910aa-b1d7-4f05-a91a-beea007e58b9',
    'vocabulary_machine_name' => 'profession',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Administrativ lås',
    'description' => '',
    'format' => 'editor',
    'weight' => 0,
    'uuid' => '66fda5fa-e6a9-419d-b5e7-154c3544f2f8',
    'vocabulary_machine_name' => 'keyword',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Teamleder',
    'description' => '',
    'format' => 'editor',
    'weight' => 15,
    'uuid' => '679721b0-2015-4aa7-92e3-daae9b1b20b0',
    'vocabulary_machine_name' => 'profession',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Ydernummer',
    'description' => '',
    'format' => 'editor',
    'weight' => 0,
    'uuid' => '696c3a76-da66-4aab-aabe-e50666220a02',
    'vocabulary_machine_name' => 'keyword',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Genoptræningsplan',
    'description' => '',
    'format' => 'editor',
    'weight' => 0,
    'uuid' => '69b5c0aa-e2de-42d1-ae24-7f4460297ec9',
    'vocabulary_machine_name' => 'keyword',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'holdtræning',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '6ae4280b-89a1-4430-b10e-0248a2adf6dc',
    'vocabulary_machine_name' => 'keyword',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Ergoterapeut',
    'description' => '',
    'format' => 'editor',
    'weight' => -12,
    'uuid' => '6ba2475e-041e-40c9-b3dc-0f873f4148d5',
    'vocabulary_machine_name' => 'profession',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Magtanvendelse',
    'description' => '',
    'format' => 'editor',
    'weight' => 0,
    'uuid' => '7087bc42-b7ac-42ec-b29e-2b433fa491ba',
    'vocabulary_machine_name' => 'subject',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'stamdata',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '71332b16-9c2b-461e-bbc7-bcb042d228c6',
    'vocabulary_machine_name' => 'keyword',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Vaccination',
    'description' => '',
    'format' => 'editor',
    'weight' => 0,
    'uuid' => '72669106-4bd5-4bd3-a1ad-bebcabd2e0c5',
    'vocabulary_machine_name' => 'keyword',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Formular',
    'description' => '',
    'format' => 'editor',
    'weight' => 0,
    'uuid' => '72c1361c-6801-4e09-8465-13c605e33514',
    'vocabulary_machine_name' => 'keyword',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Optag lås',
    'description' => '',
    'format' => 'editor',
    'weight' => 0,
    'uuid' => '740fd80b-a513-4d0f-b373-1a28d788ac00',
    'vocabulary_machine_name' => 'keyword',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Sygepleje',
    'description' => '',
    'format' => 'editor',
    'weight' => 0,
    'uuid' => '743061d0-4cdc-4421-bf5f-ea19682d9e22',
    'vocabulary_machine_name' => 'keyword',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Handlingsbeskrivelse',
    'description' => '',
    'format' => 'editor',
    'weight' => 0,
    'uuid' => '74620460-62d7-4d48-893e-6d20f588f19a',
    'vocabulary_machine_name' => 'keyword',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Sygeplejerske',
    'description' => '',
    'format' => 'editor',
    'weight' => -15,
    'uuid' => '75c6a0d5-2ffe-40c2-afee-20bde83d3f37',
    'vocabulary_machine_name' => 'profession',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Træning',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '76c4e57d-688a-4292-8571-d6caa0279005',
    'vocabulary_machine_name' => 'keyword',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'tid',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '77503a43-7773-4cea-8073-8d063790892d',
    'vocabulary_machine_name' => 'keyword',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Medicinskema',
    'description' => '',
    'format' => 'editor',
    'weight' => 0,
    'uuid' => '79980682-35a2-40e7-84ed-28e4105458e6',
    'vocabulary_machine_name' => 'keyword',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Retningsgivende mål',
    'description' => '',
    'format' => 'editor',
    'weight' => 0,
    'uuid' => '7a5acb6a-38de-4a8c-a01f-1df7e4aeb5f5',
    'vocabulary_machine_name' => 'keyword',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Elev/studerende',
    'description' => '',
    'format' => 'editor',
    'weight' => 8,
    'uuid' => '7ca29a3c-0d9b-4362-bee2-028247d218c4',
    'vocabulary_machine_name' => 'profession',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Specialark',
    'description' => '',
    'format' => 'editor',
    'weight' => 0,
    'uuid' => '7d184387-1dda-4ca5-a4b1-f7cbd221a78e',
    'vocabulary_machine_name' => 'keyword',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Borgersplan',
    'description' => '',
    'format' => 'editor',
    'weight' => 0,
    'uuid' => '7d53e70c-af1f-4669-9b76-7fef961bad80',
    'vocabulary_machine_name' => 'keyword',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Advis',
    'description' => '',
    'format' => 'editor',
    'weight' => 0,
    'uuid' => '7e8c78f6-87cc-4af0-b122-2e823797aee2',
    'vocabulary_machine_name' => 'keyword',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'test',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '7f8654b8-e1b0-4b46-8c98-7658ba528099',
    'vocabulary_machine_name' => 'keyword',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Opgradering',
    'description' => '',
    'format' => 'editor',
    'weight' => 0,
    'uuid' => '81200fc1-6a7e-4163-825a-81c65774926c',
    'vocabulary_machine_name' => 'subject',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Plejeforløbsplan',
    'description' => '',
    'format' => 'editor',
    'weight' => 0,
    'uuid' => '83784ba1-043d-4e1e-aed1-ad265320443a',
    'vocabulary_machine_name' => 'keyword',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'egen læge',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '8548c105-59df-4f77-8ddb-8ef98ef0993f',
    'vocabulary_machine_name' => 'keyword',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Konsulent',
    'description' => '',
    'format' => 'editor',
    'weight' => 12,
    'uuid' => '8a8fd137-ca1b-46b2-bb17-1a37aed1b267',
    'vocabulary_machine_name' => 'profession',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Administrativ medarbejder',
    'description' => '',
    'format' => 'editor',
    'weight' => 4,
    'uuid' => '93c2ad6e-d669-4a97-ab5c-68f8aec48276',
    'vocabulary_machine_name' => 'profession',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Kalenderplan',
    'description' => '',
    'format' => 'editor',
    'weight' => 0,
    'uuid' => '97c080bd-f981-4329-9066-cbaddd03b4d1',
    'vocabulary_machine_name' => 'keyword',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Superbruger',
    'description' => '',
    'format' => 'editor',
    'weight' => 0,
    'uuid' => '984d26e4-b903-45b2-a868-c1cd67479801',
    'vocabulary_machine_name' => 'keyword',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Udredning',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '99392c85-9aa7-46f3-ad6d-dc05db1bd744',
    'vocabulary_machine_name' => 'keyword',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Mobil (HH2 + HH3)',
    'description' => '',
    'format' => 'editor',
    'weight' => 0,
    'uuid' => '9db44fd6-e42c-4b91-8364-92cf1802e2d6',
    'vocabulary_machine_name' => 'subject',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Genoptræning',
    'description' => '',
    'format' => 'editor',
    'weight' => 0,
    'uuid' => 'a0733c2e-934a-489e-aab6-56f056e97575',
    'vocabulary_machine_name' => 'keyword',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Kommunikation',
    'description' => '',
    'format' => 'editor',
    'weight' => 0,
    'uuid' => 'a1f37618-64d7-4c0f-85b6-e9321cb9888b',
    'vocabulary_machine_name' => 'subject',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Sagsbehandling',
    'description' => '',
    'format' => 'editor',
    'weight' => 0,
    'uuid' => 'a3d4bf2f-854c-4ef0-9dc0-a7357fe4b283',
    'vocabulary_machine_name' => 'subject',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Skabelonplan',
    'description' => '',
    'format' => 'editor',
    'weight' => 0,
    'uuid' => 'a7d975db-8c37-45f8-ba07-01af2b2eb72e',
    'vocabulary_machine_name' => 'keyword',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Andet',
    'description' => '',
    'format' => 'editor',
    'weight' => 19,
    'uuid' => 'a8b77425-9dbc-4e19-908a-1e99d4362de6',
    'vocabulary_machine_name' => 'profession',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Indlæggelsesadvis',
    'description' => '',
    'format' => 'editor',
    'weight' => 0,
    'uuid' => 'aa7a3d95-fd25-4db0-9193-555f44d0cc4f',
    'vocabulary_machine_name' => 'keyword',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Netværk',
    'description' => '',
    'format' => 'editor',
    'weight' => 0,
    'uuid' => 'ac60e476-aeae-481f-b2b9-de7717c27d7c',
    'vocabulary_machine_name' => 'keyword',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Stamdata / oplysninger',
    'description' => '',
    'format' => 'editor',
    'weight' => 0,
    'uuid' => 'ac716f08-9079-4bc7-9f42-e2fcd8999731',
    'vocabulary_machine_name' => 'subject',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Tilhørsforhold',
    'description' => '',
    'format' => 'editor',
    'weight' => 0,
    'uuid' => 'b240da70-fa46-4471-ab1f-ebf1cbd02633',
    'vocabulary_machine_name' => 'keyword',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Indsatser',
    'description' => '',
    'format' => 'editor',
    'weight' => 0,
    'uuid' => 'b2d3842d-fb86-4b33-bd49-6189ad857b6e',
    'vocabulary_machine_name' => 'keyword',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Hjemmepleje',
    'description' => '',
    'format' => 'editor',
    'weight' => 0,
    'uuid' => 'b3d8eba1-ce1e-419d-9c8d-0b1f06414239',
    'vocabulary_machine_name' => 'keyword',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Medcom 7',
    'description' => '',
    'format' => 'editor',
    'weight' => 0,
    'uuid' => 'b61d5db3-9f7f-465b-8b82-35ab5ea41326',
    'vocabulary_machine_name' => 'keyword',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Diverse',
    'description' => '',
    'format' => 'editor',
    'weight' => 0,
    'uuid' => 'b6243039-39d9-46b2-93fc-9912a2c081bd',
    'vocabulary_machine_name' => 'subject',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Borgers hverdagsplan',
    'description' => '',
    'format' => 'editor',
    'weight' => 0,
    'uuid' => 'b75bc482-2155-4e5d-9720-37f9319e301c',
    'vocabulary_machine_name' => 'keyword',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Pdata',
    'description' => '',
    'format' => 'editor',
    'weight' => 0,
    'uuid' => 'b9c2e64b-7e08-463e-8f95-146260d83bba',
    'vocabulary_machine_name' => 'keyword',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Særlig info',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'ba16dce4-188a-4df6-9cbb-1772a04794a1',
    'vocabulary_machine_name' => 'keyword',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Afslut journal',
    'description' => '',
    'format' => 'editor',
    'weight' => 0,
    'uuid' => 'ba381d25-d024-446e-bd16-ef506fca3a46',
    'vocabulary_machine_name' => 'keyword',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Billede',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'bee3896d-990a-4246-8398-69215e9d43d4',
    'vocabulary_machine_name' => 'keyword',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Social- og sundhedshjælper',
    'description' => '',
    'format' => 'editor',
    'weight' => -14,
    'uuid' => 'c3c8ab9e-c53b-40fd-b446-b85b2ad6647c',
    'vocabulary_machine_name' => 'profession',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Genbestilling',
    'description' => '',
    'format' => 'editor',
    'weight' => 0,
    'uuid' => 'c4d96241-6688-4bea-846b-e09415f30131',
    'vocabulary_machine_name' => 'keyword',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Samarbejdsbog',
    'description' => '',
    'format' => 'editor',
    'weight' => 0,
    'uuid' => 'c61563f8-f27b-4071-894c-4436c9212011',
    'vocabulary_machine_name' => 'keyword',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Indlæggelsesrapport',
    'description' => '',
    'format' => 'editor',
    'weight' => 0,
    'uuid' => 'c67ca490-c494-4bd2-891f-d00e53de789f',
    'vocabulary_machine_name' => 'keyword',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Brugerprofil',
    'description' => '',
    'format' => 'editor',
    'weight' => 0,
    'uuid' => 'c86569f3-0b02-4a01-bbfe-77b3575f112c',
    'vocabulary_machine_name' => 'keyword',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Kvalifikationskrav',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'ca72aca1-cc87-40cf-8bae-94813fa4b7ac',
    'vocabulary_machine_name' => 'keyword',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Overblik',
    'description' => '',
    'format' => 'editor',
    'weight' => 0,
    'uuid' => 'cdc223a7-2892-4dea-a2ac-1644a8c72561',
    'vocabulary_machine_name' => 'subject',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Familie',
    'description' => '',
    'format' => 'editor',
    'weight' => 0,
    'uuid' => 'cf2b6f19-79ca-4b85-9bd6-132b261cecef',
    'vocabulary_machine_name' => 'keyword',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'FV',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'cf2f618f-a5db-4cae-adfa-7f6140a99b19',
    'vocabulary_machine_name' => 'keyword',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'svar',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'd01f5bdf-dd74-457d-8bef-34018ab89d17',
    'vocabulary_machine_name' => 'keyword',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Borgerkonsulent',
    'description' => '',
    'format' => 'editor',
    'weight' => 6,
    'uuid' => 'd288c5a5-67a6-4873-9f40-a9393f3a062c',
    'vocabulary_machine_name' => 'profession',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Dosisdispenseret',
    'description' => '',
    'format' => 'editor',
    'weight' => 0,
    'uuid' => 'd551b953-9a91-4be9-813a-625212266590',
    'vocabulary_machine_name' => 'keyword',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'opret journal',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'd5904881-ba68-46d6-9bf0-fa6d74b07994',
    'vocabulary_machine_name' => 'keyword',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Økonomaer/køkkenassistent/Ernæringsassistent',
    'description' => '',
    'format' => 'editor',
    'weight' => 18,
    'uuid' => 'd835fa8a-16be-46ab-826a-d4338ab5c66c',
    'vocabulary_machine_name' => 'profession',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Medicin',
    'description' => '',
    'format' => 'editor',
    'weight' => 0,
    'uuid' => 'da739ac2-23c5-4dc7-87f5-71cb5a114a07',
    'vocabulary_machine_name' => 'keyword',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Diætist',
    'description' => '',
    'format' => 'editor',
    'weight' => 7,
    'uuid' => 'dadbc379-0018-4730-96cb-0fb945ba5548',
    'vocabulary_machine_name' => 'profession',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Fokusområde',
    'description' => '',
    'format' => 'editor',
    'weight' => 0,
    'uuid' => 'db61934f-eab2-4a3b-bfb5-83ecd664c80d',
    'vocabulary_machine_name' => 'keyword',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Printmappe',
    'description' => '',
    'format' => 'editor',
    'weight' => 0,
    'uuid' => 'db67eaaf-6e6c-478b-831f-a6cb1c2ab743',
    'vocabulary_machine_name' => 'keyword',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Social- og sundhedsassistent',
    'description' => '',
    'format' => 'editor',
    'weight' => -13,
    'uuid' => 'db8553a4-69cc-4c8d-93d2-1f95746d81e0',
    'vocabulary_machine_name' => 'profession',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Udsøgning',
    'description' => '',
    'format' => 'editor',
    'weight' => 0,
    'uuid' => 'dc8735bc-3c62-43de-a22b-2115162b36a7',
    'vocabulary_machine_name' => 'keyword',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Sygesikringsoplysninger',
    'description' => '',
    'format' => 'editor',
    'weight' => 0,
    'uuid' => 'de45b67c-96fa-4913-9558-fb151ce82710',
    'vocabulary_machine_name' => 'keyword',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => '§140',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'e064c721-68b2-4726-897f-d9f098417a1f',
    'vocabulary_machine_name' => 'keyword',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Sundhedskonsulent',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'e8f4af38-bd69-4dbe-bb6c-aebf1926d839',
    'vocabulary_machine_name' => 'profession',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Værge',
    'description' => '',
    'format' => 'editor',
    'weight' => 0,
    'uuid' => 'ebbd4cbf-fbf2-4b9c-b909-ce3e619a19a4',
    'vocabulary_machine_name' => 'keyword',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'IT-koordinator',
    'description' => '',
    'format' => 'editor',
    'weight' => 11,
    'uuid' => 'eff40111-8f10-4ff7-9b81-24a4771a533f',
    'vocabulary_machine_name' => 'profession',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Frivilligkoordinator',
    'description' => '',
    'format' => 'editor',
    'weight' => 9,
    'uuid' => 'f039f55a-5a2b-468b-bc1e-b999220a78d9',
    'vocabulary_machine_name' => 'profession',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Variable medicin',
    'description' => '',
    'format' => 'editor',
    'weight' => 0,
    'uuid' => 'f081e031-dd36-4678-942b-9f6f7a73bbe3',
    'vocabulary_machine_name' => 'keyword',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Afgørelser',
    'description' => '',
    'format' => 'editor',
    'weight' => 0,
    'uuid' => 'f3bdf615-8107-4a31-9c01-fc22f3069918',
    'vocabulary_machine_name' => 'keyword',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Sygeplejeindsatser',
    'description' => '',
    'format' => 'editor',
    'weight' => 0,
    'uuid' => 'f7f39c0f-ae84-4f9c-9ede-bfe88b102350',
    'vocabulary_machine_name' => 'keyword',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Manuel advis',
    'description' => '',
    'format' => 'editor',
    'weight' => 0,
    'uuid' => 'f852a27e-384a-44b7-82ff-3ccdee1f2a8b',
    'vocabulary_machine_name' => 'keyword',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Planlægning (Booking, Disponering)',
    'description' => '',
    'format' => 'editor',
    'weight' => 0,
    'uuid' => 'fbc5014d-bb32-45cb-912c-3cfe927ffbea',
    'vocabulary_machine_name' => 'subject',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Opsætning af system (brugerprofil / indstillinger)',
    'description' => '',
    'format' => 'editor',
    'weight' => 0,
    'uuid' => 'fd6876d9-7331-4126-a33a-135f18c0d3b7',
    'vocabulary_machine_name' => 'subject',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'nødvendige oplysninger',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'fd7a2822-bb91-4be6-a1d1-d74b7c787fae',
    'vocabulary_machine_name' => 'keyword',
    'metatags' => array(),
  );
  return $terms;
}
